### ISSUE TITLE
1.3 beta appliance - field parsing errors

### ISSUE THREAD

**Issue by zexxon** [Graylog2/graylog2-images#100]
<img width="1063" alt="screen shot 2015-11-20 at 4 48 36 pm" src="https://cloud.githubusercontent.com/assets/1154318/11313937/9c63eebc-8fa6-11e5-8cd7-cafecaee1aad.png">

**Comment by mariussturm** [comment]
Fixed with https://github.com/Graylog2/graylog2-server/commit/b583aec4c4bab7d9654a3e255136e91318fbdaca
