### ISSUE TITLE
Add documentation about flags we can set in GRAYLOG_SMTP_SERVER variable

### ISSUE THREAD

**Issue by JrCs** [Graylog2/graylog2-images#104]
Hi,
I need to send some alert using SMTP but without using TLS/SSL to connect to the SMTP server. I don't find the parameters to set in the `GRAYLOG_SMTP_SERVER`value to disable TLS/SSL connections.
So can you update the documentation and describe all the options we can set in `GRAYLOG_SMTP_SERVER` variable ?

**Comment by mariussturm** [comment]
Hi Yves,
you can use this syntax for configuraring the smtp settings: ` sudo graylog-ctl set-email-config <smtp server> [–port=<smtp port> –user=<username> –password=<password> –no-tls –no-ssl]`
The last two options are relevant for you to disable tls and ssl. More commands can be found here: http://docs.graylog.org/en/latest/pages/installation/graylog_ctl.html#graylog-ctl
