### ISSUE TITLE
Changing allow_highlighting option from environment variable

### ISSUE THREAD

**Issue by JrCs** [Graylog2/graylog2-images#105]
Hi,

is it possible to change `the allow_highlighting` option from an environment variable that is pass to the docker coontainer ?

**Comment by joschi** [comment]
@JrCs Yes, you can override any configuration setting with an environment variable with the prefix `GRAYLOG2_`, so `GRAYLOG2_ALLOW_HIGHLIGHTING` will override the `allow_highlighting` setting from the configuration file.
