### ISSUE TITLE
Baked AMI needs to be cleaned

### ISSUE THREAD

**Issue by EslamElHusseiny** [Graylog2/graylog2-images#106]
`/var/lib/cloud` needs to be removed from the graylog2 AWS AMI to enable the execution of user data scripts.
I had to build a new AMI on top of graylog official one with `/var/lib/cloud` removed.

**Comment by mariussturm** [comment]
Did you remove the whole directory or the content of that directory? `rm -r /var/lib/cloud` vs. `rm -r /val/lib/cloud/*` ?

**Comment by EslamElHusseiny** [comment]
the whole directroy rm -rf /var/lib/cloud
every time you start a new instance from the AMI `/var/lib/cloud` will be created again

**Comment by mariussturm** [comment]
Thanks! Will be fixed in the next version: https://github.com/Graylog2/graylog2-images/commit/e3c95ace4b767c4d3cfebd2d118471d25d4c98a5
