### ISSUE TITLE
Dockerfile: Err http://archive.ubuntu.com trusty InRelease

### ISSUE THREAD

**Issue by Aleyasen** [Graylog2/graylog2-images#110]
I tried to build docker image by the following command:
sudo docker build -f docker/Dockerfile docker

The Dockerfile cannot resolve archive.ubuntu.com, error message:

Err http://archive.ubuntu.com trusty InRelease
Err http://archive.ubuntu.com trusty-updates InRelease
Err http://archive.ubuntu.com trusty-security InRelease
Err http://archive.ubuntu.com trusty Release.gpg
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com trusty-updates Release.gpg
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com trusty-security Release.gpg
  Could not resolve 'archive.ubuntu.com'
Reading package lists...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease  

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/InRelease  

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/InRelease  

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/Release.gpg  Could not resolve 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/Release.gpg  Could not resolve 'archive.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.

 
Complete log: https://gist.github.com/Aleyasen/201c6817bb57a1760ebe

**Comment by joschi** [comment]
Looks like a local problem to me. Make sure that your system (the one running the Docker container) can access the Internet and specifically the name servers provided in `/etc/resolv.conf`.

Also looks similar to phusion/baseimage-docker#120 (if you're running on Windows).

**Comment by Aleyasen** [comment]
Thank you very much for your reply. I used another machine and it worked.
