### ISSUE TITLE
Add tags to images published to docker hub

### ISSUE THREAD

**Issue by kimble** [Graylog2/graylog2-images#112]
Adding tags to images published to docker hub (in addition to latest) makes it a lot easier to have control of which version of Graylog that will be pulled and run.

**Comment by joschi** [comment]
Related to Graylog2/omnibus-graylog2#10.

**Comment by joschi** [comment]
Once the Omnibus package is being properly versioned, we could simply use [Automated Builds on Docker Hub](https://docs.docker.com/docker-hub/builds/).

**Comment by PatrickHuetter** [comment]
+1

**Comment by mariussturm** [comment]
This is done for the Graylog2/server image
