### ISSUE TITLE
Zombie java processes

### ISSUE THREAD

**Issue by ptman** [Graylog2/graylog2-images#113]
The docker image often ends up with zombie java processes:

    root     21132  0.0  0.0    176     4 ?        Ss   10:28   0:00      |   \_ runsv graylog-web
    1000     21367  0.0  0.1  21372  3648 ?        Ss   10:29   0:00      |   |   \_ bash /opt/graylog/web/bin/graylog-web-interface -Dconfig.file=/opt/graylog/conf/graylog-web-interface.conf -Dhttp.port=9000 -Dhttp.address=0.0.0.0 -Dpidfile.path=/var/opt/graylog/web.pid -Dlogger.file=/opt/graylog/conf/web-logger.xml
    1000     21410  0.0  0.0  21372  2084 ?        S    10:29   0:00      |   |   |   \_ bash /opt/graylog/web/bin/graylog-web-interface -Dconfig.file=/opt/graylog/conf/graylog-web-interface.conf -Dhttp.port=9000 -Dhttp.address=0.0.0.0 -Dpidfile.path=/var/opt/graylog/web.pid -Dlogger.file=/opt/graylog/conf/web-logger.xml
    1000     21411 26.4  0.0      0     0 ?        Zl   10:29   0:31      |   |   |       \_ [java] <defunct>

    1000     21167  0.0  0.0  21372  2016 ?        S    10:28   0:00      \_ bash /opt/graylog/web/bin/graylog-web-interface -Dconfig.file=/opt/graylog/conf/graylog-web-interface.conf -Dhttp.port=9000 -Dhttp.address=0.0.0.0 -Dpidfile.path=/var/opt/graylog/web.pid -Dlogger.file=/opt/graylog/conf/web-logger.xml
    1000     21168 25.6  0.0      0     0 ?        Zl   10:28   0:37      |   \_ [java] <defunct>

What can be done about it?

**Comment by mariussturm** [comment]
Could you please provide some more data to reproduce this? Host memory size and log output from the web interface would be a good start.

**Comment by ptman** [comment]
Granted, I don't have a huge amount of memory, but no OOM messages in dmesg and still plenty of memory free on this Azure DS1 instance (3.5GB RAM). And it's just when starting up, without having input any data (other than that which the docker image feeds into itself). I'll try to capture a pristine log. /var/log/graylog/web ?

**Comment by mariussturm** [comment]
Yes, /var/log/graylog/web/current it is.

**Comment by ptman** [comment]
It is actually empty when the java processes end up as zombies (consuming all available CPU). If I kill the parents of the zombie javas they reparent under my_init and runit starts a new graylog-web that logs and works. But the zombies still hang around consuming CPU.

**Comment by mariussturm** [comment]
Which operating system and version is used? Also Docker version and command line parameters of the daemon could help.

**Comment by ptman** [comment]
Debian stable. Could we maybe IM? I can give you access to the server if you'd find that convenient. It's only a test environment, after all.

**Comment by mariussturm** [comment]
Sorry pretty busy currently, if I can't reproduce it on my machine it's very hard to say how to proceed. I will try with Debian during the day and see if I get the same issue.

**Comment by mariussturm** [comment]
On a local Debian Jessie I can start the graylog2/allinone container 10 times in a row without a single zombie process so I guess this issue is somehow related to Azure. Not sure never did anything there, sorry.

**Comment by ptman** [comment]
Would you like access to my problematic test instance?

**Comment by mariussturm** [comment]
Sorry that's currently not possible.

**Comment by morallo** [comment]
Hi!
Same issue here. Running graylog2/allinone through docker-compose, I get a java zombie process, eating up 100% CPU. No way to kill it unless rebooting.

My environment:
- physical machine with 12GB RAM, Ubuntu 14.04 LTS x86_64 (with kernel 4.2.0-27-generic). 
- docker-compose version 1.6.0, build d99cad6
- Docker version 1.10.1, build 9e83765


Docker compose lines:
```yaml
    graylog:
        image: graylog2/allinone
        expose: ['12201']
        ports: ['9000:9000']
```

**Comment by ptman** [comment]
I haven't seen this with the newer graylog2/server images
