### ISSUE TITLE
us-west-2 for 1.3.3 AMI doesn't exist

### ISSUE THREAD

**Issue by jwhipp** [Graylog2/graylog2-images#116]
When attempting to use 1.3.3 for us-west-2, the follow error in AWS pops up:

"We cannot proceed with your requested configuration. This AMI (ami-27c4de46) does not exist.
The specified AMI you are trying to use has an invalid ID, does not exist, or does not exist in this region. Check the AMI details, or try again with a valid AMI."

**Comment by justinmacleod** [comment]
Looks like it's just the link that is wrong. The AMI exists if you manually look for it. The proper deeplink is: https://console.aws.amazon.com/ec2/v2/home?region=us-west-2#LaunchInstanceWizard:ami=ami-27c4de46

**Comment by mariussturm** [comment]
Thanks, should be fixed now!
