### ISSUE TITLE
Why phusion/baseimage as base image?

### ISSUE THREAD

**Issue by eabay** [Graylog2/graylog2-images#12]
Hello Marius,

Just wanted to know, is there any specific reason to choose `phusion/baseimage` over official `ubuntu:trusty`?

Thanks,

Erhan

**Comment by dreamcat4** [comment]
Hi there. Just to say that for all its benefits, the Phusion base image is rather large. Pretty much anything else will result in a smaller image size.

The best way I have found, is to be using the new official `ubuntu:16.04`. Which is the smallest supported one now. Then add into it the s6-overlay process supervisor. Which is specially made for docker images. No need for Phusion.

**Comment by mariussturm** [comment]
@dreamcat4 we are in the process of building a smaller image only with java and a minimal Graylog installed, take a look here: https://hub.docker.com/r/graylog2/server
