### ISSUE TITLE
How to upgrade existing graylog2 docker instance to newer version?

### ISSUE THREAD

**Issue by PatrickHuetter** [Graylog2/graylog2-images#120]
Hi!
I'm running graylog 1.2.x with your docker container but would like to upgrade to the newest version.
The problem is that this image provides no tags so i can't just make a backup to revert to my old version if the upgrade fails. So is it possible to upgrade by just starting a new docker container (latest) and the same configuration (same volume etc.)? Does graylog2 needed migrations itself?

Best regards

**Comment by mariussturm** [comment]
Hi Patrick,
it should be possible to start a Graylog 1.3 container with your existing data volumes but you should do a backup of your data before. Only the upgrade to major version bumps like the upcoming 2.0 will most likely be a problem. There will be tagged versions of the Docker container when I find the time.

**Comment by PatrickHuetter** [comment]
Thank you @mariussturm ! What is the preferred way to run graylog on a server? Native install (via package management like apt) or docker or otherwise?

**Comment by mariussturm** [comment]
For a permanent setup we recommend to install Graylog via APT/RPM packages. Maybe supported by our Chef/Puppet recipes if this is an option for you.
