### ISSUE TITLE
OVA for Graylog2 1.3.3 missing chpst

### ISSUE THREAD

**Issue by vtsingaras** [Graylog2/graylog2-images#124]
The solution is to install runit in the Ubuntu image. 

On a side note: Also please remove open-vm-tools as not all hypervisors are VMware! :)

**Comment by mariussturm** [comment]
Could you please elaborate what exactly you are trying to fix? Runit is installed, like everything else needed to run Graylog, under /opt/graylog in the appliances.

open-vm-tools detect if the virtual machine is VMWare or not and deactives itself.
