### ISSUE TITLE
Docker run command hang

### ISSUE THREAD

**Issue by lechen26** [Graylog2/graylog2-images#126]
Hi

i'm trying to use both graylog2/allinone:latest and allinone-beta and with both images, while trying to run a container using docker run -t -p 9000:9000 -p 12201:12201 graylog2/allinone the process just hang on execute[apt-get-update-periodic].

my Docker Host is Suse 12 and docker version "1.8.1, build 786b29d"
any idea what could be wrong?

thanks
Chen

**Comment by lechen26** [comment]
i've drill into the recipe and i see this step just execute ant update, i assume its related to my corporate proxy...

**Comment by mariussturm** [comment]
Jepp, thats right, the recipe runs `apt-get update` to make sure later package installations (ntp client) don't fail.
