### ISSUE TITLE
Elasticsearch nodes with too low open file limit 

### ISSUE THREAD

**Issue by Quentinvarquet** [Graylog2/graylog2-images#127]
Hello,

My container is running in production since 4 months and I still have this message 

`Elasticsearch nodes with too low open file limit (triggered 24 days ago)
There are Elasticsearch nodes in the cluster that have a too low open file limit (current limit: 4096 on 4d5982646e9a; should be at least 64000) This will be causing problems that can be hard to diagnose. Read how to raise the maximum number of open files`

Do you have any solution ?

Thank you

**Comment by mariussturm** [comment]
Hi,
the docker container should not restrict the open file limit. Most likely this is a resource/security setting on your host machine.

**Comment by Quentinvarquet** [comment]
Hello,

Thank you for  your answer :) 

I tryed to change the limit in /etc/security/limits.conf but I still have this error. Do I have to change another conf file ?

I saw on the docker hub : https://hub.docker.com/r/graylog2/allinone/

> In case you see warnings regarding open file limit, try to set ulimit from the outside of the container::
  $ docker run --ulimit nofile=64000:64000

Can you explain how to make it works ?

Thank you for your help !

**Comment by mariussturm** [comment]
You can try to append this option to your command line, like `docker run --ulimit nofile=64000:64000 -t -p 9000:9000 -p 12201:12201 graylog2/allinone`

**Comment by Quentinvarquet** [comment]
It works, thank you :)
