### ISSUE TITLE
mime.types for nginx is missing

### ISSUE THREAD

**Issue by sergey-litvinov** [Graylog2/graylog2-images#128]
Hi guys,

I've tried to use docker container for graylog 1.3. it works but it produces bunch of logs as `mime.types` doesn't exist and it produces a couple of such log entries each second:

> nginx: [emerg] open() "/opt/graylog/conf/nginx/mime.types" failed (2: No such file or directory) in /opt/graylog/conf/nginx/nginx.conf:9

Maybe problem that nginx that come with graylog missing this file? If i manually add that file, then it doesn't spam with that record.

Steps to reproduce are easy - just need to follow steps from graylog for docker installation guide - https://hub.docker.com/r/graylog2/allinone/

**Comment by mariussturm** [comment]
The Graylog2/allinone image is deprecated, please use the stripped down Graylog2/server instead.
