### ISSUE TITLE
Disable Automatic Content Packs

### ISSUE THREAD

**Issue by fraser-m** [Graylog2/graylog2-images#131]
Hi,

Is it possible to disable the default, automatic content packs that come with the AWS AMI image?  This would be helpful for us to make the streams, dashboards and inputs a bit easier on the eye.

Looking at the AMI, there are JSON files that are in /opt/graylog/server/contentpacks  I can remove these, however it looks like the content pack is automatically loaded into MongoDB.  Can this be disabled or do I have to run some form of Mongo script to remove them?

Cheers,
Fraser

**Comment by mariussturm** [comment]
Take a look at the content_packs_\* settings in the graylog.conf file. You can also change them by using Docker environment variables like `-e GRAYLOG_CONTENT_PACKS_LOADER_ENABLED=false`
