### ISSUE TITLE
 My Graylog Web Interface was disconnected

### ISSUE THREAD

**Issue by ghost** [Graylog2/graylog2-images#135]
My server is running and i've do the great configuration but my web interface was disconnected.
When I want to connect on my server on a browser i have this :

The web interface was unable to connect to any Graylog node in the cluster so far.

Please check that the configured nodes shown on the left hand side are correct and that the servers are reachable.

Configured nodes
http://x.x.x.x:12900
Never connected! 

Discovered nodes
None of the configured nodes could be reached recently.

I don't know what I have to do ..

**Comment by kroepke** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like it. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
