### ISSUE TITLE
Docker TLS syslog problem.

### ISSUE THREAD

**Issue by ptman** [Graylog2/graylog2-images#137]
Running the graylog2/allinone docker images, I cannot get rsyslog to send messages to graylog if I do it over the docker published port (via docker-proxy), but it works if I circumvent it.

container started using

```
docker run --name graylog ... -p 127.0.0.1:6514:6514 graylog2/allinone
```

rsyslog.conf:

```
$DefaultNetstreamDriver gtls
$DefaultNetstreamDriverCAFile ...ca.crt
$DefaultNetstreamDriverCertFile ...client.crt
$DefaultNetstreamDriverKeyFile ...client.key
$ActionSendStreamDriverAuthMode x509/certvalid
$ActionSendStreamDriverMode 1
*.* @@localhost:6514;RSYSLOG_SyslogProtocol23Format
```

No messages show up on the graylog input.

tcpdump shows the connections to be immediately terminated (RST as a response to SYN):

```
15:23:33.816348 IP6 localhost.37940 > localhost.syslog-tls: Flags [S], seq 3586804490, win 43690, options [mss 65476,sackOK,TS val 113871316 ecr 0,nop,wscale 7], length 0
15:23:33.816359 IP6 localhost.syslog-tls > localhost.37940: Flags [R.], seq 0, ack 3586804491, win 0, length 0
```

If I however check the IP address of the container using:

```
docker exec -it graylog ip a
```

and change the rsyslog forward rule to the IP address of the container instead of localhost (so that it bypasses docker-proxy listening on localhost:6514):

```
*.* @@172.17.0.9:6514;RSYSLOG_SyslogProtocol23Format
```

The messages go through.

So what is going on here? I found nothing in the logs of graylog (except an encouraging message that the TLS/TCP input was running:

```
2016-04-08_15:03:52.24901 INFO  [AbstractTcpTransport] Enabled TLS for input [Syslog TCP/5707c60de4b0b97c4bf379ab]. key-file="/server.key" cert-file="/server.crt"
```

How is docker-proxy messing with the connection? I would like to be able to use docker-proxy, as the container IP address is only accessible on the host running docker.

**Comment by mariussturm** [comment]
Sorry no idea, never used docker-proxy before.

**Comment by ptman** [comment]
have you used docker with --publish? that uses docker-proxy

**Comment by ptman** [comment]
This seems to have been a problem in docker-proxy that has been fixed in later versions

**Comment by mariussturm** [comment]
Great, thanks for the information!
