### ISSUE TITLE
Master branch readme points to version 1.34

### ISSUE THREAD

**Issue by rsteckler** [Graylog2/graylog2-images#139]
Merge the 2.0.0 branch into master, now that 2.0.0 is GA  👍

**Comment by joschi** [comment]
I'd rather keep the `1.0` and `2.0` branches (with `2.0` being the current default branch on GitHub) and remove `master` altogether.

@mariussturm What's your opinion on that?

**Comment by mariussturm** [comment]
Agree, just deleted master. 2.0 was the default already! Thanks!

**Comment by rsteckler** [comment]
The first link on [this doc page](http://docs.graylog.org/en/2.0/pages/installation/aws.html#amis) also needs to be updated to point to: `https://github.com/Graylog2/graylog2-images/tree/2.0/aws`

**Comment by joschi** [comment]
@rsteckler Thanks, we've updated the respective link (Graylog2/documentation@8f842469cfbd7e1cf8dd183a2fb360bc728fbde8).
