### ISSUE TITLE
Docker container cannot restart services after being stopped

### ISSUE THREAD

**Issue by dfch** [Graylog2/graylog2-images#14]
## Observed behaviour

After starting a container via ```docker run -d -t -i -P graylog2/allinone``` the system boots up successfully and is fully functioning (accepting log messages etc). However after issuing a ```docker stop <ContainerId>``` and then restarting this container via ```docker start <ContainerId>``` the container will run into an endless loop as the services (such as ElasticSearch and subordinate services cannot be started). One of these error messages:

	2014-12-31 10:11:34,820 ERROR: org.graylog2.initializers.IndexerSetupService - Could not connect to Elasticsearch at http://172.17.0.84:9200/, is it running?
	java.net.ConnectException: No route to host to http://172.17.0.84:9200/_nodes

	ERROR: Could not successfully connect to Elasticsearch. Check that your cluster state is not RED and that Elasticsearch is running properly.
	
	Need help?
	
	* Official documentation: http://graylog2.org/resources/documentation
	* Community support: http://graylog2.org/resources/community-support
	* Commercial support: http://graylog2.org/products
	
	But we also got some specific help pages that might help you in this case:
	
	* http://www.graylog2.org/resources/documentation/setup/elasticsearch
	
	Terminating. :(
	
## Additional notes

* It does not matter if ports are exposed via ```-P``` or separately via ```-p```

* it seems that the docker container will get a new internal IP address upon every restart, so if the startup script is not aware of the changed addresses it will probably fail as it cannot find the underlying service (cf. http://jpetazzo.github.io/2013/10/16/configure-docker-bridge-network/ and https://groups.google.com/forum/#!topic/docker-user/-FFFKhGmOtI )

* Reconfiguring graylog2 after restarting the container seems to workaround this problem:

	```docker exec -i -t <ContainerId> /usr/bin/graylog2-ctl reconfigure```

## Platform

I am running on ```CentOS 7.0 3.10.0-123.13.2.el7.x86_64``` and ```docker version```

	Client version: 1.3.2
	Client API version: 1.15
	Go version (client): go1.3.3
	Git commit (client): 39fa2fa/1.3.2
	OS/Arch (client): linux/amd64
	Server version: 1.3.2
	Server API version: 1.15
	Go version (server): go1.3.3
	Git commit (server): 39fa2fa/1.3.2

graylog2 docker image:

	REPOSITORY          TAG    IMAGE ID     CREATED    VIRTUAL SIZE
	graylog2/allinone   latest 387b6e81d77d 7 days ago 1.153 GB

**Comment by mariussturm** [comment]
The only useful solution I can see here is to ditch the bridged network completly. When I start the container like this: `docker run --net=host -t graylog2/allinone` the stop/start cycle works.

**Comment by dfch** [comment]
Hi Marius, thanks for your suggestion. However, this would only be something for use in a test environment (as the whole container is completely connected with the host). I had a look at the config of elasticsearch and graylog2 files and it seems that upon first boot the ip address is registered (rather than the hostname). It might be a better approach to register the host name in the config files (and update the hosts file upon every restart). Thanks anyway! Ronald

**Comment by mariussturm** [comment]
It would also be possible to let all services listen on `localhost` in that way no reconfiguration is needed. But this will break the ability to split services into single containers: https://github.com/Graylog2/graylog2-images/tree/master/docker#multi-container-setup which is a main idea of Docker, small services in small containers.

**Comment by mariussturm** [comment]
The restart issue should be fixed in the latest container, we connect now all services against localhost. No need to change anything after a container restart.
