### ISSUE TITLE
Allow custom plugins to docker image

### ISSUE THREAD

**Issue by onmomo** [Graylog2/graylog2-images#144]
Currently, I'm forced to copy all preinstalled graylog2 plugins to the mounted plugin directory similar as with the graylog config file:

volumes:
      - ./graylog-data/plugin:/usr/share/graylog/data/plugin

Would be useful if I could specify an additional plugin directory within the config.

**Comment by joschi** [comment]
@onmomo You can override the plugin directory with the `GRAYLOG_PLUGIN_DIR` environment variable (see https://github.com/Graylog2/graylog2-server/blob/2.0.1/misc/graylog.conf#L32-L33).

Additional plugin directories can currently not be provided.

**Comment by onmomo** [comment]
@joschi So, to use the system plugins like "graylog-plugin-map-widget" I need to copy them to the override plugin directory on my host?

**Comment by joschi** [comment]
@onmomo Yes, that's unfortunately how it works at the moment.

**Comment by onmomo** [comment]
@joschi ok, thanks a lot!
