### ISSUE TITLE
unclear plugin directory (OVA / Omnibus)

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-images#145]
Install Graylog with Omnibus (OVA) and install Plugins to Graylog. 

Got two **plugins** folder and you need to look into configuration to find out which is used. following the idea that every service that is used inside the package is in his own directory **/opt/graylog/server/plugins** would be the folder that is used for graylog server plugins. 

But in the configuration is **/opt/graylog/plugins** defined. 

For compatibility reasons the last one should be used but the first one should be a symlink .

**Comment by mariussturm** [comment]
Fixed through 8687014ce41b58f5cd3265e3e9090bf76449fa33
