### ISSUE TITLE
how to check error in log files? It needs permission or not found such directory ... please help with  ubuntu Command

### ISSUE THREAD

**Issue by aminkhodamoradi** [Graylog2/graylog2-images#148]

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
