### ISSUE TITLE
 Elasticsearch cluster unavailable 

### ISSUE THREAD

**Issue by aminkhodamoradi** [Graylog2/graylog2-images#149]
Graylog could not successfully connect to the Elasticsearch cluster. If you're using multicast, check that it is working in your network and that Elasticsearch is accessible. Also check that the cluster name setting is correct. Read how to fix this in the Elasticsearch setup documentation.
 Above error has seen in different version of ova graylog. In my case it seems that do some setting in both graylog and ES becuse of changing network and something like that. But I don't know how and what command I should use. the graylog docs are confusing me becuseof I'm not linux user but I have to use it for my project. Help me

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
