### ISSUE TITLE
Amazon AMI fails upon initial sudo graylog2-ctl reconfigure with dependency on libopts25 (>= 1:5.18)

### ISSUE THREAD

**Issue by dfch** [Graylog2/graylog2-images#15]
Just to let you know that there seems to be an issue with the Amazon AMI (as it cannot be started following the documentation at [Graylog2 AWS EC2 Images](https://github.com/Graylog2/graylog2-images/blob/master/packer/AWS.md).

# Observed behaviour

When using the current Amazon AMI (0.92.3, us-east-1, ami-ca9ff0a2) to launch an instance ```sudo graylog2-ctl reconfigure``` fails upon installing/configuring ntpd with the following error message:

	[2015-01-02T10:52:48+00:00] ERROR: apt_package[ntp] (ntp::default line 28) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
	---- Begin output of apt-get -q -y install ntp=1:4.2.6.p5+dfsg-3ubuntu2.14.04.1 ----
	STDOUT: Reading package lists...
	Building dependency tree...
	Reading state information...
	Some packages could not be installed. This may mean that you have
	requested an impossible situation or if you are using the unstable
	distribution that some required packages have not yet been created
	or been moved out of Incoming.
	The following information may help to resolve the situation:

	The following packages have unmet dependencies:
	 ntp : Depends: libopts25 (>= 1:5.18) but it is not installable
	STDERR: E: Unable to correct problems, you have held broken packages.
	---- End output of apt-get -q -y install ntp=1:4.2.6.p5+dfsg-3ubuntu2.14.04.1 ----
	Ran apt-get -q -y install ntp=1:4.2.6.p5+dfsg-3ubuntu2.14.04.1 returned 100

# Notes

* No specific information was supplied when choosing image (i.e. no kernel id etc)

```Linux ip-10-157-90-96 3.13.0-34-generic #60-Ubuntu SMP Wed Aug 13 15:45:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux```

* Manual installation of *libopt25* fails as package cannot be found (see below

```
	ubuntu@ip-10-157-90-96:~$ sudo apt-get install libopts25
	Reading package lists... Done
	Building dependency tree
	Reading state information... Done
	Package libopts25 is not available, but is referred to by another package.
	This may mean that the package is missing, has been obsoleted, or
	is only available from another source

	E: Package 'libopts25' has no installation candidate
```

* Amazon details

```Instance type c3.xlarge```
```Availability zone us-east-1d```
```AMI ID graylog2-0.92.3-1419362218 (ami-ca9ff0a2)```
```Kernel ID aki-919dcaf8```

* This is not really an important issue for me, I can work around otherwise. I just thought I let you know.

**Comment by mariussturm** [comment]
Thanks for reporting, should be fixed with us-east-1: ami-a0394ec8
