### ISSUE TITLE
Graylog There are 2 notifications

### ISSUE THREAD

**Issue by Nik0laev** [Graylog2/graylog2-images#150]
Hi all. Help to deal with the problem. install set Graylog v2.0.2 OVA Virtual Appliances. Set up node on Graylog2 server. After some time the problem appears. Tell me what to do?
![error](https://cloud.githubusercontent.com/assets/19946029/16082516/b82f00da-3322-11e6-9b44-a1ddcf2bc7e1.png)

**Comment by mariussturm** [comment]
Hi,
this looks like Elasticsearch is not running at all or very slow. This could be a result of a slow system. Please make sure that the appliance have enough resources like a fast disk and at least 4Gig of ram.

We use Github to track software bugs, please re-ask your question on our mailing list if the problem still exist.

**Comment by Nik0laev** [comment]
Please tell me where to write the query?
![sys_info](https://cloud.githubusercontent.com/assets/19946029/16082987/6acc2708-3324-11e6-9584-4dbec7f71abe.png)

**Comment by mariussturm** [comment]
https://www.graylog.org/community-support

**Comment by Nik0laev** [comment]
Thank you
