### ISSUE TITLE
IP Address Change - graylog-ctl reconfigure fails

### ISSUE THREAD

**Issue by terriblesysadmin** [Graylog2/graylog2-images#151]
Hello,

I'm running a test VM for Graylog (built from a template VM image) that is pulling an address from DHCP, I have recently changed the IP for this server but when I run graylog-ctl reconfigure to reflect that IP change in the Graylog configuration I receive the attached error.
[graylog-ctl_dump.txt](https://github.com/Graylog2/graylog2-images/files/330539/graylog-ctl_dump.txt)

The stacktrace.out content is included in the attached, and aptly named, stacktrace.txt. 
[stacktrace.txt](https://github.com/Graylog2/graylog2-images/files/330541/stacktrace.txt)

Short of rebuilding the VM from the template image again, and never changing the IP, is there a way to get this happy again?

**Comment by mariussturm** [comment]
Hi,
for some reason the Etcd service is not running on your VM. It's used by the Chef recipes to gather informations about the Graylog cluster.
Try to restart the Etcd service with `sudo graylog-ctl restart etcd` and verify that it's runing with `ps ax` before executing `graylog-ctl reconfigure`

**Comment by terriblesysadmin** [comment]
I got this squared away, noticed the partition I had mounted for /var/opt/graylog/data was full. Expanded the partition, reran graylog-ctl reconfigure and all was well. Thanks!
