### ISSUE TITLE
Graylog is restarting...

### ISSUE THREAD

**Issue by swaroopkatargunde** [Graylog2/graylog2-images#153]
Hi 

I have install the graylog2 into my Vmware Server and pushed all the logs from my network devices to the graylog.

After 1 week when i try to login the page i see the error " Graylog is restarting..." .

i tried restarting the server but no luck .

can you please help . Thanks in advance.
![image](https://cloud.githubusercontent.com/assets/5258317/16497113/05a858b0-3f13-11e6-8fb2-e1c81aff42a6.png)

**Comment by joschi** [comment]
@swaroopkatargunde We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by Segstro** [comment]
I have the same issue running the VB in windows.

**Comment by mariussturm** [comment]
@Segstro please post the problem with some context like error from the server logs to the mailing list.
