### ISSUE TITLE
Vagrant image not working - Web server is using the guest IP instead of localhost

### ISSUE THREAD

**Issue by garrmark** [Graylog2/graylog2-images#154]
after I vagrant up, I go to http://localhost:9000 and get the error 

> Error message
> Bad request
> Original Request
> GET http://10.0.2.15:12900/system/sessions
> Status code
> undefined
> Full error message
> Error: Request has been terminated Possible causes: the network is offline, Origin is not allowed by 
> Access-Control-Allow-Origin, the page is being unloaded, etc.

I tried changing the **rest_listen_uri = http://0.0.0.0:12900/** to **rest_listen_uri = http://localhost:12900/** in graylog.conf but then it doesn't look like there's anything running at port 12900 on the guest OS.

**Comment by joschi** [comment]
@garrmark This URI can be changed with the `web_endpoint_uri` configuration setting. By default, it's the value of `rest_transport_uri` (which is identical to `rest_listen_uri` if it hasn't been set or has been set to `0.0.0.0`).

**Comment by mariussturm** [comment]
@garrmark should be fixed now, please use the latest Vagrant file and access the web interface via `http://localhost:8080`

**Comment by garrmark** [comment]
Yes, it works now, thank you.
