### ISSUE TITLE
Setting Heap size with Docker

### ISSUE THREAD

**Issue by philicious** [Graylog2/graylog2-images#155]
So I found #82 and #84 and wonder if setting `/etc/graylog/graylog-settings.json` + `graylog-ctl reconfigure` is still the suggested way to alter heap sizes with Docker.

I would rather like to set `GRAYLOG_SERVER_JAVA_OPTS` env var as used by docker-entrypoint.sh
Can this approach be considered save? 

(I know about graylog mem management in general. Now, for the first time, I have to slim down the graylog container and squeeze some memory out of it grrr)

**Comment by mariussturm** [comment]
If you use the graylog2/server image the environment variable is the way to go. The graylog-ctl solution is for the deprecated graylog2/allinone image.

**Comment by philicious** [comment]
ah perfect then. 

Maybe put that info into some doc or wiki. While searching I couldnt find it
