### ISSUE TITLE
Graylog is restarting...

### ISSUE THREAD

**Issue by legonzalez1** [Graylog2/graylog2-images#156]
Hi Support
Greetings

Excuse me, after install Graylog2 is not able to display the webpage, I have the next messaje "Graylog is restarting..."

I have checked the status services and it seems that is correct

ubuntu@graylog:~$ sudo graylog-ctl status
run: elasticsearch: (pid 906) 1327s; run: log: (pid 861) 1328s
run: etcd: (pid 907) 1327s; run: log: (pid 904) 1327s
run: graylog-server: (pid 1773) 294s; run: log: (pid 853) 1328s
run: mongodb: (pid 905) 1327s; run: log: (pid 862) 1328s
run: nginx: (pid 903) 1328s; run: log: (pid 854) 1328s

Could you indicate me if is necessary to check any else?

I have installed the OVA appliance

![graylog_issue](https://cloud.githubusercontent.com/assets/20690789/17192969/869c2fa6-5416-11e6-827a-cfa1de767d67.PNG)

**Comment by edmundoa** [comment]
Hi,

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
