### ISSUE TITLE
Support ova image using CentOS 7 ?

### ISSUE THREAD

**Issue by tjyang** [Graylog2/graylog2-images#157]
Hi There

Is there a plan to support graylog2 ova using CentOS 7 ?
I was able to follow the doc to build my own graylog2 on centos 7 VMWare VM, but I am hoping I can just download it to simply the configuration effort for centos users.

**Comment by joschi** [comment]
@tjyang No, there are no plans to provide an omnibus package (which the OVA is based on, see https://github.com/Graylog2/omnibus-graylog2) for CentOS 7.
