### ISSUE TITLE
Server does not start after disk extend

### ISSUE THREAD

**Issue by eduanb** [Graylog2/graylog2-images#162]
I have a Graylog v2.0.3 server deployed from the OVA on vmware. I extended the disk exactly as per http://docs.graylog.org/en/2.0/pages/configuration/graylog_ctl.html but now the server does not want to start up. From the web page it says "Graylog is restarting...". The only relevant log which I could find:

`2016-08-22_11:57:22.19766 2016-08-22 13:57:22,197 INFO : org.mongodb.driver.cluster - No server chosen by WritableServerSelector from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, all=[ServerDescription{address=127.0.0.1:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused}}]}. Waiting for 30000 ms before timing out`

Any suggestions?

**Comment by mariussturm** [comment]
Looks like MongoDB is nor running anymore. Could you please check the logs in /var/log/graylog/mongodb/current. Also try to restart mongodb with graylog-ctl.

**Comment by eduanb** [comment]
Yes it seems like mongodb does not want to start up.
Found this in /var/log/graylog/mongodb/current:
`exception in initAndListen: 29 Data directory /var/opt/graylog/data/mongodb not found., terminating`

Restarting with `sudo graylog-ctl restart mongodb` does not work since that directory does not exist. Any suggestions how to recover what should be there or rather revert the snapshot and retry extending the disk?

**Comment by mariussturm** [comment]
I guess you have mounted a new disk volume over /var/opt/graylog/data to increase the disk space but you didn't copy the content from the old directory to that disk. So I would unmount that volume, copy the old the data, re-mount and try again.

**Comment by eduanb** [comment]
Yeah It seams like that. Will revert the snapshot, retry and report.

**Comment by mariussturm** [comment]
Closig this for now, feel free to add more comments if you think this is a bug.

**Comment by eduanb** [comment]
Hi I found the issue. The very last step `
echo "/dev/sdb1 /var/opt/graylog/data ext4 \\
defaults 0 0" \| sudo tee -a /etc/fstab
` did not make the mount permanent for me. I had to manually remount after the reboot.

**Comment by mariussturm** [comment]
Alright, but I think the command is correct. At least on my machine it creates a valid fstab entry.
