### ISSUE TITLE
rest_listen_uri and web_listen_uri use the same port in docker/config/graylog.conf

### ISSUE THREAD

**Issue by harobed** [Graylog2/graylog2-images#164]
Hi,

there are a mistake in https://github.com/Graylog2/graylog2-images/blob/07aaa4bfa0b4e7d8e99de53fc493e441202f84e4/docker/config/graylog.conf

`rest_listen_uri` and `web_listen_uri` use the same port!

```
rest_listen_uri = http://0.0.0.0:9000/api/
web_listen_uri = http://0.0.0.0:9000/
```

if web and rest services use the same port then you have this error:

```
Failed to start Grizzly HTTP server: Address already in use
```

**Comment by mariussturm** [comment]
This will be supported in Graylog 2.1.0.

**Comment by harobed** [comment]
Yes but I've lost 2h because this error, I'm suggest to fix this bug and wait that Graylog 2.1.0 be released.

**Comment by mariussturm** [comment]
This is already part of the release preparation and only in the git repository, if you stick to the pre-build images here: https://hub.docker.com/r/graylog2/server/
you dont lose a single second of your time.

**Comment by harobed** [comment]
Ok.

Next time, I suggest you to work in `develop` branch.

**Comment by harobed** [comment]
@mariussturm but https://github.com/Graylog2/graylog2-server/blob/master/misc/graylog.conf configuration is bad, this url is indicated in this screenshot:

![capture d ecran 2016-08-30 a 18 48 52](https://cloud.githubusercontent.com/assets/230143/18098421/6cf27948-6ee2-11e6-8dc0-30ee1863231d.png)

**Comment by mariussturm** [comment]
Not related to issue, locking this.
