### ISSUE TITLE
Vagrant file not working out of the box

### ISSUE THREAD

**Issue by hedii** [Graylog2/graylog2-images#168]
Hi, The vagrant image is not working out of the box:
- OS X 10.11.6 (15G1004)
- Vagrant 1.8.5
- VirtualBox 5.0.26 r108824
- Vagrant file: https://raw.githubusercontent.com/Graylog2/graylog2-images/2.1/vagrant/Vagrantfile

After a successful vagrant up, i go to http://localhost:8080/

```
Server currently unavailable

We are experiencing problems connecting to the Graylog server running on http://127.0.0.1:12900/. Please verify that the server is healthy and working correctly.

You will be automatically redirected to the previous page once we can connect to the server.

Do you need a hand? We can help you.

Less details
This is the last response we received from the server:

Error message
Bad request
Original Request
GET http://127.0.0.1:12900/system/sessions
Status code
undefined
Full error message
Error: Request has been terminated Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
```

And there is nothing on http://127.0.0.1:12900

<img width="643" alt="screen shot 2016-09-09 at 10 13 47" src="https://cloud.githubusercontent.com/assets/5358048/18380118/24b84e78-7676-11e6-9548-4963252d2220.png">

**Comment by mariussturm** [comment]
Fixed in the latest version, please update your Vagrantfile.
