### ISSUE TITLE
Latest OVA graylog-2.1.1-1.ova has Ensoniq sound card embedded as a required device

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog2-images#170]
_From @bubba198 on September 21, 2016 20:20_

Latest OVA graylog-2.1.1-1.ova has Ensoniq sound card embedded as a required device
## Expected Behavior

Error when deploying using ESXi or any other VM player that happens to NOT have any sound device defined
## Possible Solution

Edit the XML which is a hassle but perfectly legit way to get rid of the error and be able to deploy the OVA
## Steps to Reproduce (for bugs)

1. Attempt to deploy graylog-2.1.1-1.ova on a hypervisor which does NOT have sound card
   2.
   3.
   4.
## Your Environment

ESXi 5.0 custom HP Pro Liant image
- Graylog Version: graylog-2.1.1-1.ova
- Elasticsearch Version: graylog-2.1.1-1.ova
- MongoDB Version: graylog-2.1.1-1.ova
- Operating System: graylog-2.1.1-1.ova
- Browser version: Chrome latest 64 bit

_Copied from original issue: Graylog2/graylog2-server#2877_

**Comment by nicozanf** [comment]
This bug is still present in graylog-pre-2.2.0-alpha.4-1.ova

**Comment by mariussturm** [comment]
I have disabled the sound card now and rebuild graylog-pre-2.2.0-alpha.4-1.ova!

**Comment by bubba198** [comment]
What about graylog-2.1.1-1.ova ? Has it been re-generated too? Thanks

**Comment by nicozanf** [comment]
I do confirm that it's fixed on graylog-pre-2.2.0-alpha.4-1.ova , 2016-10-21T14:58:52.000Z version. Thank you!

**Comment by bubba198** [comment]
@nicozanf thanks for checking that; any idea about graylog-2.1.1-1.ova ? Thanks

**Comment by joschi** [comment]
@bubba198 The OVA has been rebuilt, just download it again from https://packages.graylog2.org/appliances/ova
