### ISSUE TITLE
proxy issue with AWS image

### ISSUE THREAD

**Issue by MorganCloud** [Graylog2/graylog2-images#171]
hello everyone, 
I have an issue at work with graylog I'd like help with please...I installed graylog from scratch within my AWS environment using the websites AMI, and everything was setup for me.I have a AWS VPC  and all traffic goes through a load balancer or proxy on port 80. I ave opened port 9000 as well. My issue is when I open port 80 and 9000 for where the server is located everything works(but this is against my companies policy, so traffic should be routed through the proxy), but I am unable to proxy port 80 traffic to the public ip address and the private ip address doesnt work.

my proxy config is below:

```
<VirtualHost *:80>
    ServerName logserver.net
    ServerAlias logserver
    ProxyRequests off
    ProxyPreserveHost On
<Location />
    ProxyPass http://10.1.80.23:9000/
    ProxyPassReverse http://10.1.80.23:9000/
        Order allow,deny
          Allow from all
</Location>

</VirtualHost>
```

I also proxy passed port 80 traffic because on the server it uses nginx as a proxy as well.

**Comment by joschi** [comment]
@AmorganICUC We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Please also include some more details about the actual error you're seeing.

Thank you!
