### ISSUE TITLE
Current OVA stable image (2.1.1) has sound card device

### ISSUE THREAD

**Issue by suretek1** [Graylog2/graylog2-images#173]
Hello - the current OVA image has a sound card device, which caused me problems importing to my ESXi server.  Would think that it should be removed for greater compatibility across hypervisors.  To work around I simply extracted the contents of the OVA container and edited the actual OVA inside to remove the sound card device.

**Comment by bubba198** [comment]
I believe that was just fixed today at around 8am PST?

**Comment by joschi** [comment]
We've just rebuilt the OVA 2.1.1-1 to include the patch from #170.
