### ISSUE TITLE
Expanded disk size, but Graylog will not start now

### ISSUE THREAD

**Issue by tommerp** [Graylog2/graylog2-images#176]
Hi there

I've run out of space on my Graylog server and needed to expand my disk.  I've expanded my disk size using the directions from here ( http://docs.graylog.org/en/2.0/pages/configuration/graylog_ctl.html#extend-disk-space ) but now the server does not seem to want to start up.  On the webpage, I get a "Graylog is restarting" yet it never moves past that.  

![image](https://cloud.githubusercontent.com/assets/23384199/20184175/c51dd096-a735-11e6-8212-9a07308fe9dc.png)

I've also attempted to search for errors in log files, but I'm not able to get into them due to permissions. (/var/log/graylog/*/current)

How can I get it restarted or running again?

Thanks!

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
