### ISSUE TITLE
Graylog is restarting...

### ISSUE THREAD

**Issue by tomaszwielechowski** [Graylog2/graylog2-images#177]
Hi

I'm part of the problem, at the entrance to the site:

Graylog is restarting...

There is no Graylog web application running at the moment, please reload this page in a minute. It can take up to 1-2 minutes until all services are running properly. In case this is a permanent error, check the following:

Check if all services are running - sudo graylog-ctl status shows an overview of all running services
Check for errors in log files - Relevant services write log files here: /var/log/graylog/*/current
Ask for help - If there is no way to fix the issue ask for help: https://github.com/Graylog2/graylog2-images/issues

from what I noticed is df -h shows me 100% occupancy / dev / dm-0

ubuntu@graylog:/var/log/graylog$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            987M   12K  987M   1% /dev
tmpfs           200M  420K  200M   1% /run
/dev/dm-0        15G   15G     0 100% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
none            5.0M     0  5.0M   0% /run/lock
none            998M     0  998M   0% /run/shm
none            100M     0  100M   0% /run/user
/dev/xvda1      236M   41M  183M  19% /boot
overflow        1.0M  140K  884K  14% /tmp
ubuntu@graylog:/var/log/graylog$

what can I do in this situation?

Regards Thomas.

**Comment by mariussturm** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by tomaszwielechowski** [comment]
Thanks :)
