### ISSUE TITLE
Vagrant provisioning does not finish

### ISSUE THREAD

**Issue by fnk** [Graylog2/graylog2-images#179]
The host environment is OSX 10.11.6

Following the setup instructions from http://docs.graylog.org/en/latest/pages/installation/vagrant.html the provisioning step hangs at following point (Curl download of graylog deb file):

`==> default: Going to download Graylog...`

Whe i execute `vagrant@graylog:~$ curl -S -s -L -O https://packages.graylog2.org/releases/graylog-omnibus/ubuntu/graylog_latest.deb` inside the vm manually, i get following error:

`curl: (23) Failed writing body (0 != 4260)`

replacing the `curl` command with `wget` solves the issue for me.

**Comment by mariussturm** [comment]
Thanks for the report!
Looks like a temporary problem with S3, nothing we can fix from our side. We will monitor this and take action when the problem persist.
