### ISSUE TITLE
after rebooting graylog unable to access graylog server

### ISSUE THREAD

**Issue by musmans** [Graylog2/graylog2-images#180]
ubuntu@graylog-beta:~$ sudo graylog-ctl reconfigure
Starting Chef Client, version 12.6.0
Compiling Cookbooks...
Recipe: graylog::default
  * directory[/etc/graylog] action create (up to date)
  Converging 122 resources
Recipe: apt::default
  * file[/var/lib/apt/periodic/update-success-stamp] action nothing (skipped due                                                                                         to action :nothing)
  * directory[/etc/apt/apt.conf.d] action create (up to date)
  * cookbook_file[/etc/apt/apt.conf.d/15update-stamp] action create (up to date)
  * execute[apt-get update] action nothing (skipped due to action :nothing)
  * execute[apt-get autoremove] action nothing (skipped due to action :nothing)
  * execute[apt-get autoclean] action nothing (skipped due to action :nothing)
  * execute[apt-get-update-periodic] action run

^C[2016-12-26T12:53:39+05:00] FATAL: SIGINT received, stopping
[2016-12-26T12:53:39+05:00] FATAL: SIGINT received, stopping
/opt/graylog/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.0.7/lib/omnibus-ctl.rb:172:in `system': Interrupt
        from /opt/graylog/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.0.7/lib/omnibus-ctl.rb:172:in `run_command'
        from /opt/graylog/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.0.7/lib/omnibus-ctl.rb:279:in `reconfigure'
        from /opt/graylog/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.0.7/lib/omnibus-ctl.rb:366:in `run'
        from /opt/graylog/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.0.7/bin/omnibus-ctl:27:in `<top (required)>'
        from /opt/graylog/embedded/bin/omnibus-ctl:23:in `load'
        from /opt/graylog/embedded/bin/omnibus-ctl:23:in `<main>'
ubuntu@graylog-beta:~$ sudo graylog-ctl reconfigure
[2016-12-26T12:53:41+05:00] WARN: Chef client 10567 is running, will wait for it to finish and then run.
[2016-12-26T12:53:42+05:00] ERROR: execute[apt-get-update-periodic] (apt::default line 84) had an error: SystemExit: exit; ignore_failure is set, continuing

    ================================================================================
    Error executing action `run` on resource 'execute[apt-get-update-periodic]'
    ================================================================================

    SystemExit
    ----------
    exit

    Resource Declaration:
    ---------------------
    # In /opt/graylog/embedded/cookbooks/apt/recipes/default.rb

     84: execute 'apt-get-update-periodic' do
     85:   command 'apt-get update'
     86:   ignore_failure true
     87:   timeout 90
     88:   only_if { apt_installed? }
     89:   not_if { apt_up_to_date? }
     90:   notifies :touch, 'file[/var/lib/apt/periodic/update-success-stamp]', :immediately
     91: end
     92:

    Compiled Resource:
    ------------------
    # Declared in /opt/graylog/embedded/cookbooks/apt/recipes/default.rb:84:in `from_file'

    execute("apt-get-update-periodic") do
      action [:run]
      ignore_failure true
      retries 0
      retry_delay 2
      default_guard_interpreter :execute
      command "apt-get update"
      backup 5
      returns 0
      timeout 90
      declared_type :execute
      cookbook_name :apt
      recipe_name "default"
      not_if { #code block }
      only_if { #code block }
    end

  * directory[/var/cache/local] action create (up to date)
  * directory[/var/cache/local/preseeding] action create (up to date)
  * template[/etc/apt/apt.conf.d/10recommends] action create (up to date)
  * apt_package[apt-transport-https] action install (up to date)
Recipe: graylog::default
  * directory[/etc/graylog] action nothing (skipped due to action :nothing)
Recipe: graylog::users
  * group[graylog] action create (up to date)
  * user[graylog] action create (up to date)
  * directory[/var/opt/graylog] action create (up to date)
  * template[/var/opt/graylog/.gitconfig] action create (up to date)
  * directory[/var/opt/graylog/data] action create (up to date)
Recipe: graylog::authbind
  * directory[/etc/authbind/byport] action create (up to date)
  * file[/etc/authbind/byport/!514] action create (up to date)
Recipe: runit::upstart
  * cookbook_file[/etc/init/graylog-runsvdir.conf] action create (up to date)
  * execute[initctl status graylog-runsvdir] action run
    - execute initctl status graylog-runsvdir
  * execute[initctl start graylog-runsvdir] action run (skipped due to only_if)
Recipe: runit::svloggelfd
  * cookbook_file[/opt/graylog/embedded/cookbooks/cache/svloggelfd-0.2.1.tar.gz] action create (up to date)
  * execute[extract svloggelfd] action run (skipped due to not_if)
Recipe: timezone-ii::default
  * apt_package[tzdata] action install (up to date)
Recipe: timezone-ii::debian
  * template[/etc/timezone] action create (up to date)
  * bash[dpkg-reconfigure tzdata] action nothing (skipped due to action :nothing)
Recipe: graylog::etcd
  * directory[/var/log/graylog/etcd] action create (up to date)
  * directory[/var/opt/graylog/data/etcd] action create (up to date)
  * directory[/opt/graylog/sv/etcd] action create (up to date)
  * directory[/opt/graylog/sv/etcd/log] action create (up to date)
  * directory[/opt/graylog/sv/etcd/log/main] action create (up to date)
  * template[/opt/graylog/sv/etcd/run] action create (up to date)
  * template[/opt/graylog/sv/etcd/log/run] action create (up to date)
  * template[/var/log/graylog/etcd/config] action create (up to date)
  * ruby_block[reload etcd svlogd configuration] action nothing (skipped due to action :nothing)
  * file[/opt/graylog/sv/etcd/down] action delete (up to date)
  * link[/opt/graylog/init/etcd] action create (up to date)
  * link[/opt/graylog/service/etcd] action create (up to date)
  * ruby_block[supervise_etcd_sleep] action run (skipped due to not_if)
  * service[etcd] action nothing (skipped due to action :nothing)
  * execute[/opt/graylog/embedded/bin/graylog-ctl start etcd] action run
    - execute /opt/graylog/embedded/bin/graylog-ctl start etcd
Recipe: graylog::elasticsearch
  * directory[/var/log/graylog/elasticsearch] action create (up to date)
  * directory[/var/opt/graylog/data/elasticsearch] action create (up to date)
  * directory[/opt/graylog/elasticsearch/config/scripts] action create (up to date)
  * template[/opt/graylog/elasticsearch/config/elasticsearch.yml] action create (up to date)
  * template[/opt/graylog/elasticsearch/config/logging.yml] action create (up to date)
  * link[/opt/graylog/conf/elasticsearch] action create (up to date)
  * directory[/opt/graylog/sv/elasticsearch] action create (up to date)
  * directory[/opt/graylog/sv/elasticsearch/log] action create (up to date)
  * directory[/opt/graylog/sv/elasticsearch/log/main] action create (up to date)
  * template[/opt/graylog/sv/elasticsearch/run] action create
    - update content in file /opt/graylog/sv/elasticsearch/run from 44f798 to 4ab9f8
    --- /opt/graylog/sv/elasticsearch/run       2016-12-17 14:12:16.097158651 +0500
    +++ /opt/graylog/sv/elasticsearch/.run20161226-10567-1hsiwo0        2016-12-26 12:53:46.127106296 +0500
    @@ -20,7 +20,7 @@
       -XX:CMSInitiatingOccupancyFraction=75
       -XX:+UseCMSInitiatingOccupancyOnly
       -XX:+HeapDumpOnOutOfMemoryError"
    -export ES_HEAP_SIZE=2371m
    +export ES_HEAP_SIZE=24143m
     export JAVA_HOME=/opt/graylog/embedded/jre

     exec chpst -P -U graylog -u graylog $ES_HOME/bin/elasticsearch
  * template[/opt/graylog/sv/elasticsearch/log/run] action create (up to date)
  * template[/var/log/graylog/elasticsearch/config] action create (up to date)
  * ruby_block[reload elasticsearch svlogd configuration] action nothing (skipped due to action :nothing)
  * file[/opt/graylog/sv/elasticsearch/down] action delete (up to date)
  * link[/opt/graylog/init/elasticsearch] action create (up to date)
  * link[/opt/graylog/service/elasticsearch] action create (up to date)
  * ruby_block[supervise_elasticsearch_sleep] action run (skipped due to not_if)
  * service[elasticsearch] action nothing (skipped due to action :nothing)
  * execute[/opt/graylog/embedded/bin/graylog-ctl start elasticsearch] action run
    - execute /opt/graylog/embedded/bin/graylog-ctl start elasticsearch
  * ruby_block[add node to cluster list] action run
    - execute the ruby block add node to cluster list
Recipe: graylog::mongodb
  * directory[/var/log/graylog/mongodb] action create (up to date)
  * directory[/var/opt/graylog/data/mongodb] action create (up to date)
  * directory[/opt/graylog/sv/mongodb] action create (up to date)
  * directory[/opt/graylog/sv/mongodb/log] action create (up to date)
  * directory[/opt/graylog/sv/mongodb/log/main] action create (up to date)
  * template[/opt/graylog/sv/mongodb/run] action create (up to date)
  * template[/opt/graylog/sv/mongodb/log/run] action create (up to date)
  * template[/var/log/graylog/mongodb/config] action create (up to date)
  * ruby_block[reload mongodb svlogd configuration] action nothing (skipped due to action :nothing)
  * file[/opt/graylog/sv/mongodb/down] action delete (up to date)
  * link[/opt/graylog/init/mongodb] action create (up to date)
  * link[/opt/graylog/service/mongodb] action create (up to date)
  * ruby_block[supervise_mongodb_sleep] action run (skipped due to not_if)
  * service[mongodb] action nothing (skipped due to action :nothing)
  * execute[/opt/graylog/embedded/bin/graylog-ctl start mongodb] action run
    - execute /opt/graylog/embedded/bin/graylog-ctl start mongodb
Recipe: graylog::graylog-server
  * directory[/var/log/graylog/server] action create (up to date)
  * directory[/var/opt/graylog/data/journal] action create (up to date)
  * file[/var/opt/graylog/graylog-server-node-id] action create (up to date)
  * template[/opt/graylog/conf/graylog.conf] action create (up to date)
  * template[/opt/graylog/conf/log4j2.xml] action create (up to date)
  * directory[/opt/graylog/sv/graylog-server] action create (up to date)
  * directory[/opt/graylog/sv/graylog-server/log] action create (up to date)
  * directory[/opt/graylog/sv/graylog-server/log/main] action create (up to date)
  * template[/opt/graylog/sv/graylog-server/run] action create (up to date)
  * template[/opt/graylog/sv/graylog-server/log/run] action create (up to date)
  * template[/var/log/graylog/server/config] action create (up to date)
  * ruby_block[reload graylog-server svlogd configuration] action nothing (skipped due to action :nothing)
  * file[/opt/graylog/sv/graylog-server/down] action delete (up to date)
  * link[/opt/graylog/init/graylog-server] action create (up to date)
  * link[/opt/graylog/service/graylog-server] action create (up to date)
  * ruby_block[supervise_graylog-server_sleep] action run (skipped due to not_if)
  * service[graylog-server] action nothing (skipped due to action :nothing)
  * execute[/opt/graylog/embedded/bin/graylog-ctl start graylog-server] action run
    - execute /opt/graylog/embedded/bin/graylog-ctl start graylog-server
  * ruby_block[add node to server list] action run

    ================================================================================
    Error executing action `run` on resource 'ruby_block[add node to server list]'
    ================================================================================

    Errno::ECONNREFUSED
    -------------------
    Connection refused - connect(2) for "127.0.0.1" port 4001

    Cookbook Trace:
    ---------------
    /opt/graylog/embedded/cookbooks/graylog/libraries/registry.rb:17:in `set_master'
    /opt/graylog/embedded/cookbooks/graylog/recipes/graylog-server.rb:84:in `block (2 levels) in from_file'

    Resource Declaration:
    ---------------------
    # In /opt/graylog/embedded/cookbooks/graylog/recipes/graylog-server.rb

     82: ruby_block "add node to server list" do
     83:   block do
     84:     $registry.set_master
     85:     $registry.add_gl_server(node['ipaddress'])
     86:     $registry.add_es_node(node['ipaddress'])
     87:   end
     88: end

    Compiled Resource:
    ------------------
    # Declared in /opt/graylog/embedded/cookbooks/graylog/recipes/graylog-server.rb:82:in `from_file'

    ruby_block("add node to server list") do
      action [:run]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      block_name "add node to server list"
      declared_type :ruby_block
      cookbook_name :graylog
      recipe_name "graylog-server"
      block #<Proc:0x00000005061ad0@/opt/graylog/embedded/cookbooks/graylog/recipes/graylog-server.rb:83>
    end

Running handlers:
[2016-12-26T12:53:48+05:00] ERROR: Running exception handlers
Running handlers complete
[2016-12-26T12:53:48+05:00] ERROR: Exception handlers complete
Chef Client failed. 7 resources updated in 45 seconds
[2016-12-26T12:53:48+05:00] FATAL: Stacktrace dumped to /opt/graylog/embedded/cookbooks/cache/chef-stacktrace.out
[2016-12-26T12:53:48+05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-12-26T12:53:48+05:00] ERROR: ruby_block[add node to server list] (graylog::graylog-server line 82) had an error: Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 4001
Starting Chef Client, version 12.6.0
Compiling Cookbooks...
Recipe: graylog::default
  * directory[/etc/graylog] action create (up to date)
  Converging 122 resources
Recipe: apt::default
  * file[/var/lib/apt/periodic/update-success-stamp] action nothing (skipped due to action :nothing)
  * directory[/etc/apt/apt.conf.d] action create (up to date)
  * cookbook_file[/etc/apt/apt.conf.d/15update-stamp] action create (up to date)
  * execute[apt-get update] action nothing (skipped due to action :nothing)
  * execute[apt-get autoremove] action nothing (skipped due to action :nothing)
  * execute[apt-get autoclean] action nothing (skipped due to action :nothing)
  * execute[apt-get-update-periodic] action run
    - execute apt-get update
  * file[/var/lib/apt/periodic/update-success-stamp] action touch
    - update utime on file /var/lib/apt/periodic/update-success-stamp
  * directory[/var/cache/local] action create (up to date)
  * directory[/var/cache/local/preseeding] action create (up to date)
  * template[/etc/apt/apt.conf.d/10recommends] action create (up to date)
  * apt_package[apt-transport-https] action install (up to date)
Recipe: graylog::default
  * directory[/etc/graylog] action nothing (skipped due to action :nothing)
Recipe: graylog::users
  * group[graylog] action create (up to date)
  * user[graylog] action create (up to date)
  * directory[/var/opt/graylog] action create (up to date)
  * template[/var/opt/graylog/.gitconfig] action create (up to date)
  * directory[/var/opt/graylog/data] action create (up to date)
Recipe: graylog::authbind
  * directory[/etc/authbind/byport] action create (up to date)
  * file[/etc/authbind/byport/!514] action create (up to date)
Recipe: runit::upstart
  * cookbook_file[/etc/init/graylog-runsvdir.conf] action create (up to date)
  * execute[initctl status graylog-runsvdir] action run
    - execute initctl status graylog-runsvdir
  * execute[initctl start graylog-runsvdir] action run (skipped due to only_if)
Recipe: runit::svloggelfd
  * cookbook_file[/opt/graylog/embedded/cookbooks/cache/svloggelfd-0.2.1.tar.gz] action create (up to date)
  * execute[extract svloggelfd] action run (skipped due to not_if)
Recipe: timezone-ii::default
  * apt_package[tzdata] action install (up to date)
Recipe: timezone-ii::debian
  * template[/etc/timezone] action create (up to date)
  * bash[dpkg-reconfigure tzdata] action nothing (skipped due to action :nothing)
Recipe: graylog::etcd
  * directory[/var/log/graylog/etcd] action create (up to date)
  * directory[/var/opt/graylog/data/etcd] action create (up to date)
  * directory[/opt/graylog/sv/etcd] action create (up to date)
  * directory[/opt/graylog/sv/etcd/log] action create (up to date)
  * directory[/opt/graylog/sv/etcd/log/main] action create (up to date)
  * template[/opt/graylog/sv/etcd/run] action create (up to date)
  * template[/opt/graylog/sv/etcd/log/run] action create (up to date)
  * template[/var/log/graylog/etcd/config] action create (up to date)
  * ruby_block[reload etcd svlogd configuration] action nothing (skipped due to action :nothing)
  * file[/opt/graylog/sv/etcd/down] action delete (up to date)
  * link[/opt/graylog/init/etcd] action create (up to date)
  * link[/opt/graylog/service/etcd] action create (up to date)
  * ruby_block[supervise_etcd_sleep] action run (skipped due to not_if)
  * service[etcd] action nothing (skipped due to action :nothing)
  * execute[/opt/graylog/embedded/bin/graylog-ctl start etcd] action run
    - execute /opt/graylog/embedded/bin/graylog-ctl start etcd
Recipe: graylog::elasticsearch
  * directory[/var/log/graylog/elasticsearch] action create (up to date)
  * directory[/var/opt/graylog/data/elasticsearch] action create (up to date)
  * directory[/opt/graylog/elasticsearch/config/scripts] action create (up to date)
  * template[/opt/graylog/elasticsearch/config/elasticsearch.yml] action create (up to date)
  * template[/opt/graylog/elasticsearch/config/logging.yml] action create (up to date)
  * link[/opt/graylog/conf/elasticsearch] action create (up to date)
  * directory[/opt/graylog/sv/elasticsearch] action create (up to date)
  * directory[/opt/graylog/sv/elasticsearch/log] action create (up to date)
  * directory[/opt/graylog/sv/elasticsearch/log/main] action create (up to date)
  * template[/opt/graylog/sv/elasticsearch/run] action create (up to date)
  * template[/opt/graylog/sv/elasticsearch/log/run] action create (up to date)
  * template[/var/log/graylog/elasticsearch/config] action create (up to date)
  * ruby_block[reload elasticsearch svlogd configuration] action nothing (skipped due to action :nothing)
  * file[/opt/graylog/sv/elasticsearch/down] action delete (up to date)
  * link[/opt/graylog/init/elasticsearch] action create (up to date)
  * link[/opt/graylog/service/elasticsearch] action create (up to date)
  * ruby_block[supervise_elasticsearch_sleep] action run (skipped due to not_if)
  * service[elasticsearch] action nothing (skipped due to action :nothing)
  * execute[/opt/graylog/embedded/bin/graylog-ctl start elasticsearch] action run
    - execute /opt/graylog/embedded/bin/graylog-ctl start elasticsearch
  * ruby_block[add node to cluster list] action run
    - execute the ruby block add node to cluster list
Recipe: graylog::mongodb
  * directory[/var/log/graylog/mongodb] action create (up to date)
  * directory[/var/opt/graylog/data/mongodb] action create (up to date)
  * directory[/opt/graylog/sv/mongodb] action create (up to date)
  * directory[/opt/graylog/sv/mongodb/log] action create (up to date)
  * directory[/opt/graylog/sv/mongodb/log/main] action create (up to date)
  * template[/opt/graylog/sv/mongodb/run] action create (up to date)
  * template[/opt/graylog/sv/mongodb/log/run] action create (up to date)
  * template[/var/log/graylog/mongodb/config] action create (up to date)
  * ruby_block[reload mongodb svlogd configuration] action nothing (skipped due to action :nothing)
  * file[/opt/graylog/sv/mongodb/down] action delete (up to date)
  * link[/opt/graylog/init/mongodb] action create (up to date)
  * link[/opt/graylog/service/mongodb] action create (up to date)
  * ruby_block[supervise_mongodb_sleep] action run (skipped due to not_if)
  * service[mongodb] action nothing (skipped due to action :nothing)
  * execute[/opt/graylog/embedded/bin/graylog-ctl start mongodb] action run
    - execute /opt/graylog/embedded/bin/graylog-ctl start mongodb
Recipe: graylog::graylog-server
  * directory[/var/log/graylog/server] action create (up to date)
  * directory[/var/opt/graylog/data/journal] action create (up to date)
  * file[/var/opt/graylog/graylog-server-node-id] action create (up to date)
  * template[/opt/graylog/conf/graylog.conf] action create (up to date)
  * template[/opt/graylog/conf/log4j2.xml] action create (up to date)
  * directory[/opt/graylog/sv/graylog-server] action create (up to date)
  * directory[/opt/graylog/sv/graylog-server/log] action create (up to date)
  * directory[/opt/graylog/sv/graylog-server/log/main] action create (up to date)
  * template[/opt/graylog/sv/graylog-server/run] action create (up to date)
  * template[/opt/graylog/sv/graylog-server/log/run] action create (up to date)
  * template[/var/log/graylog/server/config] action create (up to date)
  * ruby_block[reload graylog-server svlogd configuration] action nothing (skipped due to action :nothing)
  * file[/opt/graylog/sv/graylog-server/down] action delete (up to date)
  * link[/opt/graylog/init/graylog-server] action create (up to date)
  * link[/opt/graylog/service/graylog-server] action create (up to date)
  * ruby_block[supervise_graylog-server_sleep] action run (skipped due to not_if)
  * service[graylog-server] action nothing (skipped due to action :nothing)
  * execute[/opt/graylog/embedded/bin/graylog-ctl start graylog-server] action run
    - execute /opt/graylog/embedded/bin/graylog-ctl start graylog-server
  * ruby_block[add node to server list] action run

    ================================================================================
    Error executing action `run` on resource 'ruby_block[add node to server list]'
    ================================================================================

    Errno::ECONNREFUSED
    -------------------
    Connection refused - connect(2) for "127.0.0.1" port 4001

    Cookbook Trace:
    ---------------
    /opt/graylog/embedded/cookbooks/graylog/libraries/registry.rb:17:in `set_master'
    /opt/graylog/embedded/cookbooks/graylog/recipes/graylog-server.rb:84:in `block (2 levels) in from_file'

    Resource Declaration:
    ---------------------
    # In /opt/graylog/embedded/cookbooks/graylog/recipes/graylog-server.rb

     82: ruby_block "add node to server list" do
     83:   block do
     84:     $registry.set_master
     85:     $registry.add_gl_server(node['ipaddress'])
     86:     $registry.add_es_node(node['ipaddress'])
     87:   end
     88: end

    Compiled Resource:
    ------------------
    # Declared in /opt/graylog/embedded/cookbooks/graylog/recipes/graylog-server.rb:82:in `from_file'

    ruby_block("add node to server list") do
      action [:run]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      block_name "add node to server list"
      declared_type :ruby_block
      cookbook_name :graylog
      recipe_name "graylog-server"
      block #<Proc:0x000000051c02f0@/opt/graylog/embedded/cookbooks/graylog/recipes/graylog-server.rb:83>
    end

Running handlers:
[2016-12-26T12:54:27+05:00] ERROR: Running exception handlers
Running handlers complete
[2016-12-26T12:54:27+05:00] ERROR: Exception handlers complete
Chef Client failed. 8 resources updated in 45 seconds
[2016-12-26T12:54:27+05:00] FATAL: Stacktrace dumped to /opt/graylog/embedded/cookbooks/cache/chef-stacktrace.out
[2016-12-26T12:54:27+05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-12-26T12:54:27+05:00] ERROR: ruby_block[add node to server list] (graylog::graylog-server line 82) had an error: Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 4001
[2016-12-26T12:54:27+05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
ubuntu@graylog-beta:~$

**Comment by jalogisch** [comment]
@musmans it looks like you first killed the *graylog-ctl reconfigure* and then run it again.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
