### ISSUE TITLE
tag 2.1.3-1 missing

### ISSUE THREAD

**Issue by phoefflin** [Graylog2/graylog2-images#182]
On dockerhub there's a version 2.1.3-1 available but there's no corresponding tag on this repo. I understand this repo should be the base for the dockerhub builds.  Can you please give a hint, which commit the dockerhub image 2.1.3-1 is based on or else add a tag to the corresponding commit?

The reason for this request are some internal security requirements when using non-official docker images.

Thanks

**Comment by joschi** [comment]
@phoefflin Thanks for pointing this out!

I've added the [2.1.3-1](https://github.com/Graylog2/graylog2-images/releases/tag/2.1.3-1) tag for the respective commit.
