### ISSUE TITLE
Issues getting Web Interface to load while attempting to cluster to elastisearch node

### ISSUE THREAD

**Issue by IzzyCrawford** [Graylog2/graylog2-images#183]
I have added an elastisearch node to cluster. The reason for this was to remove some of the errors, This was recommended through multiple post. After that everything is was good for about 1 month then email started failing. I have alerts setup on 3 major streams, We did not receive any errors for failing servers. Now, I have been having issue for the past week or so. The web page will not load at all for graylog at all. 
I have uploaded the config file to determine if there is something that I am missing that would cause the web interface to not work properly.
[graylog.txt](https://github.com/Graylog2/graylog2-images/files/769089/graylog.txt)

**Comment by joschi** [comment]
@IzzyCrawford `rest_listen_uri` and `web_listen_uri` need to be different.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
