### ISSUE TITLE
 Launch EC2 instance failure

### ISSUE THREAD

**Issue by jun283** [Graylog2/graylog2-images#187]
I try to install to EC2 2 times, but all failure. status check donot pass. SSH cannot connect .
 
http://docs.graylog.org/en/2.2/pages/installation/aws.html
-> us-east-1 -> t2.2xlarge

**Comment by mariussturm** [comment]
Hi,
sorry can not reproduce this, for me this works fine. The minimal steps on AWS are:

  * Start the instance
  * Open port SSH(22) and HTTP(80) in your security group
  * Tell Graylog what's the external IP of the instance is: `sudo graylog-ctl set-external-ip http://52.23.XX.YY:9000/api`
  * Run `sudo graylog-ctl reconfigure`
  * Open 52.23.XX.YY in your browser and login with admin:admin

Please verify your setup, hope that helps.
