### ISSUE TITLE
No Web UI after upgrade

### ISSUE THREAD

**Issue by Zpunky** [Graylog2/graylog2-images#189]
New to Graylog.
Installed graylog-pre-2.2.0-rc.1-1.ova in my hypervisor.
Logged into web UI and it indicated there was an update.
Followed online docs to wget the update, and restarted. (ya, did not check the web UI...)
Proceeded to create the admin and service users for mongoDB per docs (had to use sudo as non-sudo produced errors) 
Ran sudo graylog-ctl reconfigure
Tried accessing the UI and it said "Greylag is restarting"
Followed instructions to check status, everything is running
Tried looking in the various service directories, 'access denied'.

Tried restarting, still no access to WenUI
[Graylog_tail.txt](https://github.com/Graylog2/graylog2-images/files/923070/Graylog_tail.txt)

There is no OVA for the most current version, most recent is the RC I used.
Attaching a portion of the tail.

services running
----------
ubuntu@graylog-beta:~$ sudo graylog-ctl status
run: elasticsearch: (pid 907) 653s; run: log: (pid 889) 653s
run: etcd: (pid 901) 653s; run: log: (pid 890) 653s
run: graylog-server: (pid 7196) 0s; run: log: (pid 891) 653s
run: mongodb: (pid 914) 653s; run: log: (pid 897) 653s
run: nginx: (pid 909) 653s; run: log: (pid 894) 653s

**Comment by joschi** [comment]
@Zpunky 
> There is no OVA for the most current version, most recent is the RC I used.

That's incorrect. Please download the latest stable version of the virtual machine image: https://packages.graylog2.org/releases/graylog-omnibus/ova/graylog-2.2.3-1.ova

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by Zpunky** [comment]
Thanks for the link, I was looking at the [GrayLog download](https://packages.graylog2.org/appliances/ova) page referenced by the [online Support docs](http://docs.graylog.org/en/2.2/pages/installation/virtual_machine_appliances.html).

**Comment by joschi** [comment]
@Zpunky The same file is listed on these pages.

But I'm glad you could solve your problem.
