### ISSUE TITLE
Unable to use custom graylog.conf to point to contentpacks

### ISSUE THREAD

**Issue by muellerk22** [Graylog2/graylog2-images#190]
I’m unable to use customer contentpacks to stock UI configuration between docker runs.

The main issue is the default config file is unable to be overwritten as this documentation states:  http://docs.graylog.org/en/latest/pages/installation/docker.html#settings

During the docker run the graylogctl is not called which I believe is used to override defaults with environment variables.  

The Dockerfile calls `` ENTRYPOINT ["/docker-entrypoint.sh"] ``

Docker-entrypoint.sh starts graylog and forces the default config file. code snippet below.

"# Start Graylog server"
  set -- gosu graylog "$JAVA_HOME/bin/java" $GRAYLOG_SERVER_JAVA_OPTS \
      -jar \
      -Dlog4j.configurationFile=/usr/share/graylog/data/config/log4j2.xml \
      -Djava.library.path=/usr/share/graylog/lib/sigar/ \
      -Dgraylog2.installation_source=docker /usr/share/graylog/graylog.jar \
      server \
### ==> 	-f /usr/share/graylog/data/config/graylog.conf    <==

The entrypoint.sh should use the environment variable for the config file or maybe use graylogctl?

Cheers,

**Comment by joschi** [comment]
> which I believe is used to override defaults with environment variables.

No, this is a functionality of Graylog itself and overriding configuration settings via environment variables works exactly as described in the documentation at http://docs.graylog.org/en/2.2/pages/installation/docker.html#settings.

I'm not sure what issue you're describing. Please elaborate on the problem you have.

**Comment by muellerk22** [comment]
I'm not using docker-compose as the documentation suggest.  The page also says there is another options.  

> Another option would be to store the configuration file outside of the container and edit it directly.

The is the option I am taking.  In this option however, there does not seem to be a way to get the startup to use a none default configuration option unless to use your own dockerfile and create a new image.  Not a terrible option mind you.  if you be nice if the docker entrypoint script could use an environment variable like graylogctl.  

The Dockerfile in the image passes a absolute link when starting graylog.  See the code snippet I  included above.  The -f option in bold above is '-f /usr/share/graylog/data/config/graylog.conf`  if this was environment variable the could be overridded when calling docker run would enable pointing to a mounted volume versus trying to replace the /use/share/graylog/data/conf directory.

**Comment by joschi** [comment]
You can override the volume mounted inside the container at `/usr/share/graylog/data/config/` as described at http://docs.graylog.org/en/2.2/pages/installation/docker.html#persist-log-data.

If you don't use docker-compose, you can still mount your own volume with your custom configuration file via Docker, see https://docs.docker.com/engine/tutorials/dockervolumes/#mount-a-host-directory-as-a-data-volume
