### ISSUE TITLE
failed to send test alert notification

### ISSUE THREAD

**Issue by maryxu** [Graylog2/graylog2-images#191]
Hello guys, I've a problem when I'm sending a test alert notification to my email address. Here's the configuration file I modified. The graylog 2.2.3 is deployed by using OVF.
root@graylog:~# cat /etc/graylog/graylog-settings.json
{
  "timezone": "Etc/UTC",
  "smtp_server": "10.119.13.185",
  "smtp_port": 25,
  "smtp_user": "#####@activenetwork.com",
  "smtp_password": "secret",
  "smtp_from_email": "#####@activenetwork.com",
  "smtp_web_url": "http://10.148.10.###/",
  "smtp_no_tls": false,
  "smtp_no_ssl": true,
  "master_node": "10.148.10.###",
  "local_connect": false,
  "current_address": "10.148.10.###",
  "last_address": "10.148.10.###",
  "enforce_ssl": false,
  "journal_size": 1,
  "node_id": false,
  "internal_logging": true,
  "web_listen_uri": false,
  "web_endpoint_uri": false,
  "rest_listen_uri": false,
  "rest_transport_uri": false,
  "external_rest_uri": false,
  "custom_attributes": {

  }
}
![error](https://cloud.githubusercontent.com/assets/13269986/25838751/2bfaff90-34c7-11e7-9016-28db4d2e9c1c.png)

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
