### ISSUE TITLE
Allow changing the elasticsearch/mongo database hosts based on ENV

### ISSUE THREAD

**Issue by trajano** [Graylog2/graylog2-images#192]
Per https://docs.docker.com/compose/compose-file/#links 

> This option is ignored when deploying a stack in swarm mode with a (version 3) Compose file.

Which means we  would need to have a custom Dockerfile that overrides the configuration rather than setting it up via `docker-compose.yml`

**Comment by mariussturm** [comment]
In the end the compose file is just an example on how the services are connected to each other. If the links are not working in your setup you can simply replace the Graylog configuration file and put whatever you want in there: http://docs.graylog.org/en/latest/pages/installation/docker.html#persist-log-data
Look for this: https://github.com/Graylog2/graylog2-images/blob/2.3/docker/config/graylog.conf#L350
and
https://github.com/Graylog2/graylog2-images/blob/2.3/docker/config/graylog.conf#L209

**Comment by trajano** [comment]
Yes I understand I am trying to make it more robust for other people so they do not need to go through too many steps.  Much like MariaDB it does most of what people would need at least to get something out the door.

The one you have already does most, just wanted to add a couple more to at least make people not be surprised why things do not work when they follow the `docker stack` examples.  Especially with the Versiion "3" docker-compose files.

**Comment by mariussturm** [comment]
Docker-compose without any special network is the most basic thing people can do so I would leave that as the default. People can easily try that out.
If you want something different you can overwrite all settings with `GRAYLOG_` ENV settings. So for example changing the MongoDB host should work with:  `GRAYLOG_MONGODB_URI`
No idea if that helps for your use-case?

**Comment by trajano** [comment]
That would help is that documented somewhere?

**Comment by mariussturm** [comment]
Yes: http://docs.graylog.org/en/latest/pages/installation/docker.html#configuration
