### ISSUE TITLE
Graylog is restarting

### ISSUE THREAD

**Issue by ghost** [Graylog2/graylog2-images#194]
I just built up a new GrayLog server instance.  After going through the configuration, I opened a browser and went tried accessing the GUI, but I'm getting a message that it's restarting.  I checked the status and all appears to be running.  There's nothing in the log.

**Comment by ghost** [comment]
![restarting](https://user-images.githubusercontent.com/13461658/27597951-966f6d9c-5b29-11e7-9910-9fa69b331ad8.jpg)

![status](https://user-images.githubusercontent.com/13461658/27597961-a01ab5a4-5b29-11e7-95c1-9a54953b41f3.jpg)

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
