### ISSUE TITLE
ova virtual image not usable

### ISSUE THREAD

**Issue by gaganova** [Graylog2/graylog2-images#195]
I just downloaded and startet up this image:
https://packages.graylog2.org/releases/graylog-omnibus/ova/graylog-2.2.3-1.ova

It is not usable - it starts up and I can login, but I see errors in the interface, the most important one may be: 
```
Elasticsearch cluster unavailable (triggered 39 minutes ago)
Graylog could not successfully connect to the Elasticsearch cluster. If you're using multicast, check that it is working in your network and that Elasticsearch is accessible. Also check that the cluster name setting is correct. Read how to fix this in the Elasticsearch setup documentation.
```

I was assuming that this virtual machine is an all-in-one thing, so I do not have to setup an ES cluster? 

Also the virtual machine is using extremely much cpu cycles, with very high "top" percentages.

Overall I had a very good impression reading the graylog docs and the whole setup seemed so right, unfortunately the real life experience with the virtual machine is very disappointing.

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by mariussturm** [comment]
@gaganova high cpu utilization is normally a sign for a process that is constantly restarting (most likely Elasticsearch in your case) please check that the VM has enough memory (at least 4GB) and try to re-import the image. But as @joschi said we provide general installation support in our forum.

**Comment by gaganova** [comment]
This was not a support request, I just wanted to make you aware of the bad experience that one makes with your virtual appliance. I am not interested in digging deeper atm with something that produces errors oob with the "showcase virtual appliance".
