### ISSUE TITLE
Connection refused) while connecting to upstream

### ISSUE THREAD

**Issue by dschmidtadv** [Graylog2/graylog2-images#197]
I'm running Graylog on AWS. After running for a number of weeks, the Web UI stopped working, and I see the following errors in the Nginx log:
2017/07/10 20:03:50 [error] 31144#0: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 173.203.27.52, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/", host: "34.194.0.149"
Any suggestions would be appreciated.

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
