### ISSUE TITLE
Graylog2 not launching properly under docker/coreos. 

### ISSUE THREAD

**Issue by tberch** [Graylog2/graylog2-images#20]
Im running into an issue when trying to run this as a container under coreos/docker

docker run -t -p 9000:9000 -p 12201:12201 graylog2/allinone

https://gist.github.com/tberch/517fe6e5613436ebdcbc

I am able to get it working under boot2docker though.

can you please try to recreate? I am held up on this project until I can get this resolved.

**Comment by tberch** [comment]
any luck with this in your test environment?

**Comment by mariussturm** [comment]
Unfortunately I can't reproduce the problem you ran into. On a latest CoreOS (alpha release) everything works just fine. I tried with a 4GB machine. Are there any other limiting factors in your setup? E.g. is `dmesg` saying about killed processes or memory problems?

**Comment by mariussturm** [comment]
Can you double check that you run the latest `graylog2/allinone` contianer, ID should be: 60d445b40140

**Comment by tberch** [comment]
it launched this time... you can close this...  I dont think I did anything different, but who knows.

**Comment by mariussturm** [comment]
Ok, strange. Feel free to reopen the ticket when you encounter the problem again.
