### ISSUE TITLE
What is the root password of Graylog OVF , need to edit the etc interfaces files for setting up the static Ip for network connection

### ISSUE THREAD

**Issue by amitsharmagraylog** [Graylog2/graylog2-images#207]

**Comment by amitsharmagraylog** [comment]
May be i am wrong but I was surprised at every graylog tutorial, the people mentioning that edit the /etc/networks/interfaces file for static address but nobody mentioned the root password for the ubuntu..

**Comment by joschi** [comment]
@amitsharmagraylog You can use `sudo` to gain root privileges, e. g. `vim /etc/networks/interfaces` to edit the network configuration with vim.

The password for the user "ubuntu" is "ubuntu" and mentioned in the documentation for the OVA:
http://docs.graylog.org/en/2.4/pages/installation/virtual_machine_appliances.html#logging-in
