### ISSUE TITLE
Documentation improvements: Production use and security

### ISSUE THREAD

**Issue by cstuder** [Graylog2/graylog2-images#21]
Thank you for these images, awesome!

A suggestion concerning the documentation:
  - Maybe make clearer whether these images are production ready or not. I know that the quick setup app isn't and spells it out so.
  - Add a section about after-installation security. Like changing the ubuntu-user-password in the OVA image.

**Comment by mariussturm** [comment]
Thanks for the heads-up, just added an additional section to the documentation.
