### ISSUE TITLE
aws webserver return 502 Bad Gateway  nginx/1.10.3 (Ubuntu) when i create an image of current instance.

### ISSUE THREAD

**Issue by shakticmexpertise** [Graylog2/graylog2-images#210]
Hello 

I am working on a project where I need to do autoscaling so I had gone through with some tutorials on youtube.where they teched that create an image of your currently running instance. so I created an image for my current instance but after creating an image my sites and everything has been stopped. and it's only returning an error like this: `502 Bad Gateway  nginx/1.10.3 (Ubuntu)` Please if anyone can help out me.
Thank you

**Comment by mariussturm** [comment]
Hi,
especially on AWS you have usually an internal and external IP address, this needs some extra configuration. Did you followed our documentation over here: http://docs.graylog.org/en/2.4/pages/installation/aws.html

For further question please consult our Discourse forum: https://community.graylog.org/
