### ISSUE TITLE
Graylog is restarting...

### ISSUE THREAD

**Issue by dpcloud** [Graylog2/graylog2-images#213]
Dear Team,

we have configured graylog server but after few days it is continuously showing that Graylog is restarting...

please provide resolution for the same and also note the status of running services..

run: elasticsearch: (pid 14963) 2s; run: log: (pid 789) 56868s
run: etcd: (pid 810) 56868s; run: log: (pid 794) 56868s
run: graylog-server: (pid 19135) 11958s; run: log: (pid 787) 56868s
down: mongodb: 1s, normally up, want up; run: log: (pid 786) 56868s
run: nginx: (pid 793) 56868s; run: log: (pid 788) 56868s

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
