### ISSUE TITLE
Docker-entrypoint failing on read-only config mounts (e.g. kubernetes configmap)

### ISSUE THREAD

**Issue by rwrnet** [Graylog2/graylog2-images#215]
https://github.com/Graylog2/graylog2-images/blob/0e911ab4e4bde90bd354662e68bdd01533d18ae7/docker/docker-entrypoint.sh#L20

Since pretty recent versions, Kubernetes mounts its configmaps as read-only filesystem. As the docker-entrypoint.sh is unconditionally trying to change the ownership of files in custom sections like config or plugins, the image stopped working.

I don't think it is good practice to manipulate the files at startup. If its part of the image, you should handle it on build. If its overlayed with a mount, you should't touch it either.

**Comment by juliohm1978** [comment]
Running into the same issue after upgrading to Kubernetes 1.10.

[Kubernete's devs are well assertive on this point](https://github.com/kubernetes/kubernetes/issues/61414). ConfigMap volumes are mounted by kubelet and it reserves the assumption that it owns the contents of the ConfigMap.

By definition, ConfigMaps should be immutable to the container. Previous versions of Kubernetes allowed changes to be made on that volume, but Pods that assumed these changes were persistent failed or became inconsistent after restart.

Regardless of how Kubernetes works, Docker itself allows volumes to be mounted as read-only. The container cannot make the assumption of owning its contents.

**Comment by DonMartin76** [comment]
Just as a short addendum: There is a feature gate flag you can set to `false` to revert to the old behavior up to Kubernetes 1.11: `ReadOnlyAPIDataVolumes=false`. **Disclaimer**: This partly takes back the security fix which introduced this change. A fix in Graylog (as proposed in #216) would be a lot better.
