### ISSUE TITLE
Graylog ova 2.4.3 default Appliance input dont start

### ISSUE THREAD

**Issue by pierrick-openIT** [Graylog2/graylog2-images#217]
Hello,

that is normal on a fresh appliance install that the default Appliance gelf input are bind on 514 ? It couldn't start due to java breach.

**Comment by joschi** [comment]
Please refer to file:///Users/joschi/Work/documentation/_build/html/pages/faq.html#how-do-i-fix-the-deflector-exists-as-an-index-and-is-not-an-alias-error-message

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
