### ISSUE TITLE
Update Ubuntu version to 18.04LTS

### ISSUE THREAD

**Issue by radykal-com** [Graylog2/graylog2-images#219]
Hello,

Actually, all Graylog images are based on Ubuntu 14.04LTS and according to https://www.ubuntu.com/info/release-end-of-life it is gonna reach end of life early next year.

To avoid providing images with an unsupported version of the OS (missing security patches) I suggest to go straight and update the version to the latest release version 18.04LTS that was released past April so it will have support for the next 5 years.

As far I know, these images are build thanks to the omnibus-package so I will also open and link an issue in the omnibus project so we can work on it. 

It is not critical to fix it just now, as there are still some months until it reaches EOL but keep the issue open to don't forget it.

**Comment by mariussturm** [comment]
Fixed for 3.0 appliances.
