### ISSUE TITLE
API Docs in API Browser not available - blocked by CORS

### ISSUE THREAD

**Issue by krzotr** [Graylog2/graylog2-images#221]
When I go to `http://192.168.1.22/api/api-browser/` I do not see any API documentation notes.

![graylog-server-3 0 0-3](https://user-images.githubusercontent.com/655681/47951502-ce412e00-df61-11e8-830d-2460b7380efa.png)

Google Chrome console shows:

    Access to XMLHttpRequest at 'http://192.168.1.22:9000/api/api-docs' from origin 'http://192.168.1.22' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, http://192.168.1.22', but only one is allowed.

Looks like something is wrong with Graylog Server configuration. If I visit `http://192.168.1.22:9000/api/api-browser/` (port 9000 instead of default 80) everything works fine.

Tested on **graylog-3.0.0-3.alpha.3.ova**

**Comment by mariussturm** [comment]
Hi,
did you typed in the API URL manually? The link on System->Nodes->Api Browser points to `http://serverIP:9000/...` and that's actually the right URL.

**Comment by krzotr** [comment]
I typed API URL manually.

In Graylog 2.4.6 I used `http://192.168.1.22/api/api-browser/` and everything was fine. No I know, I visited incorrect URL. I should visit `System->Nodes->Api Browser` to get proper API URL.

**Comment by mariussturm** [comment]
:+1:
