### ISSUE TITLE
Problems importing the OVA file into esxi 6.5 and 5.1

### ISSUE THREAD

**Issue by nathjnair** [Graylog2/graylog2-images#224]
While trying to deploy graylog 3 , the wizard stops by giving the message both for esxi 6.5 and 5.1
Line 66: OVF hardware element 'ResourceType' with instance ID '5': No support for the virtual hardware device type '35'
![image](https://user-images.githubusercontent.com/46620641/51071070-44a09180-1671-11e9-8836-6d42c425d249.png)
![image](https://user-images.githubusercontent.com/46620641/51071097-cb556e80-1671-11e9-85a7-0c469ca13101.png)

**Comment by mariussturm** [comment]
We saw similar problem with the CD drive: Device ID 6 errors

**Comment by mariussturm** [comment]
Closing this in favour of https://github.com/Graylog2/graylog2-images/issues/211
