### ISSUE TITLE
add 'action.auto_create_index: false' to elasticsearch configuration

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-images#225]
I can notice in the community that Elasticsearch is not always on the fastest machine and the index and deflector creation is slower - so that data is ingested before the indices and aliases are given. 

To avoid auto-creation and having the deflector as alias we should make this default (as we already place that into the documentation step-by-step guides.

`action.auto_create_index: false`

**Comment by mariussturm** [comment]
Fixed in https://github.com/Graylog2/graylog2-images/commit/003889b13b96bf2b8d6daebaa0ad30c5ab5066b3
