### ISSUE TITLE
Availability of AMI in eu-north-1 (Stockholm)

### ISSUE THREAD

**Issue by elion** [Graylog2/graylog2-images#235]
Please deploy Graylog AMI to eu-north-1 (Stockholm).

**Comment by malcyon** [comment]
Tried running this today, but it seems our version of packer doesn't support that region. I'm going to move the build for this over to our new Jenkins instance tomorrow and ensure it's on the latest version of packer. Hopefully that will help.

**Comment by malcyon** [comment]
@elion This AMI should work for you: ami-0eee905b56ffd3e51
