### ISSUE TITLE
Allow images in other regions?

### ISSUE THREAD

**Issue by victorhooi** [Graylog2/graylog2-images#25]
Would it be possible to also make this image in other regions?

(For example, our current deployment is in the `ap-southeast-2` region - hence, it would make sense to have a graylog2 box in that region as well), but just having any regions outside the US/EU would be good.

**Comment by mariussturm** [comment]
Thanks for the feedback!
I have add southeast-2 to the build scripts, till the next release you can use this ami: ami-b577038f
