### ISSUE TITLE
username and passowrd 

### ISSUE THREAD

**Issue by ahmed121288** [Graylog2/graylog2-images#254]
the username and password for wab access not work so if i try to change the passowrd we can not the graylog ctl file not found how can you help me with that and i try to use username admin and pawword admin in web access of gray log no work

**Comment by patrickmann** [comment]
Please refer to the doc sections on Settings, e.g. here:
https://go2docs.graylog.org/5-0/downloading_and_installing_graylog/docker_installation.htm

You can also get help in the community forums at:
https://community.graylog.org/faq

Provide as much detailed information about your setup as possible when posting to the forum.
