### ISSUE TITLE
How to update GrayLog to the fresh version?

### ISSUE THREAD

**Issue by ZedZipDev** [Graylog2/graylog2-images#255]
How to update GrayLog to the latest version in this Ubuntu VM? 
I have tried to do as GrayLog site recommends but received some warnings about Mongodb.

Or may be there is another VM with GrayLog?

**Comment by ZedZipDev** [comment]
I have upgraded GrayLog in this Ubuntu but:
the previous version: web page http://<vmip>:9000 - works
the upgraded version to GL 6 : http://<vmip>:9000  - 404

How to fix it?

**Comment by patrickmann** [comment]
@ZedZipDev Please ask your question in the [GL community forum](https://community.graylog.org/). You will get help there much more quickly, both from community members and GL staff.
This repo is intended only for bugs and feature requests, not general support.
Thank you.
