### ISSUE TITLE
console username/pass for openstack img

### ISSUE THREAD

**Issue by shaiss** [Graylog2/graylog2-images#31]
I know there is no need to login to the console.  Except 1, I need to know what IP the DHCP server assigned it.  Yes, I can connect to the DHCP server and query for the newest host, but this isn't always practical.  I tried ubuntu/ubuntu and admin/admin.  Anything else it could be?

**Comment by mariussturm** [comment]
The appliance support cloud-init, so it uses the ssh-key you set during launch in the OpenStack web interface. Username is 'ubuntu'.

**Comment by shaiss** [comment]
I'm running the qcow img in proxmox.  So it's not through the openstack web interface.

**Comment by mariussturm** [comment]
As far as I now Proxmox not related to OpenStack at all. But the image was build and optimized for OpenStack. I will try to reproduce your issue with plain KVM

**Comment by mariussturm** [comment]
I double checked this, the login is disabled by default. So you need the cloud-init process of OpenStack to deploy your ssh key to the appliance. With plain KVM/Proxmox there is no way to login.

The only thing you could do is to mount the image and enable the login back. This would work like this:

```
sudo qemu-nbd -c /dev/nbd0 graylog.qcow2
sudo mount /dev/nbd0p1 /mnt
sudo vi /mnt/etc/shadow
<remove the leading "!" infront of the password hash of the ubuntu user>
sudo umount /mnt
sudo qemu-nbd -d /dev/nbd0
```
Start the appliance again, the login should now be enabled!
