### ISSUE TITLE
Automatically adjust Elasticsearch HEAP size

### ISSUE THREAD

**Issue by tristanbob** [Graylog2/graylog2-images#32]
It appears that the heap size for Elasticsearch is supposed to be set automatically set to 50% of total memory:

https://github.com/Graylog2/omnibus-graylog2/blob/1.0.0-1/files/graylog-cookbooks/graylog/recipes/elasticsearch.rb#L35

However, on my VM with 16 GB of memory I am not sure if it is using the right HEAP size (unless I am reading my PS output wrong, which could be the case):

ubuntu@graylog:/opt/graylog/elasticsearch/config$ free -h
             total       used       free     shared    buffers     cached
Mem:           15G       7.4G       8.2G       512K       173M       5.3G
-/+ buffers/cache:       2.0G        13G
Swap:         4.0G         0B       4.0G

ubuntu@graylog:/opt/graylog/elasticsearch/config$ ps faux | grep elasticsearch
root       884  0.0  0.0   4212   440 ?        Ss   Feb19   0:00  \_ runsv elasticsearch
root       898  0.0  0.0   4356   580 ?        S    Feb19   0:00  |   \_ svlogd -tt /var/log/graylog/elasticsearch
graylog   6137  5.5  3.5 10015160 583852 ?     Ssl  Feb19  57:16  |   \_ /opt/graylog/embedded/jre/bin/java -Xms256m -Xmx1g -Xss256k -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -server -Djava.net.preferIPv4Stack=true -Des.config=/opt/graylog/conf/elasticsearch.yml -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=3333 -Xms128m -Xmx8024m -Xss256k -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=1 -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -Delasticsearch -Des.foreground=yes -Des.path.home=/opt/graylog/elasticsearch -cp :/opt/graylog/elasticsearch/lib/*:/opt/graylog/elasticsearch/lib/sigar/*:/opt/graylog/elasticsearch/lib/elasticsearch-1.4.1.jar:/opt/graylog/elasticsearch/lib/*:/opt/graylog/elasticsearch/lib/sigar/* org.elasticsearch.bootstrap.Elasticsearch

Thanks!

**Comment by tristanbob** [comment]
The confusing part is that it looks like the max memory is being set twice?

"-Xmx1g" and "-Xmx8024m"

**Comment by mariussturm** [comment]
Right, the idea was to reserve 50% of memory automatically for ES, I will double check if it sets the options right

**Comment by mariussturm** [comment]
Fixed here https://github.com/Graylog2/omnibus-graylog2/commit/ce3af69317901da75595939d538d2798b6c06ec5 Will be part of the next verions, thanks for the report!
