### ISSUE TITLE
Enable HTTPS on Graylog OVA appliance

### ISSUE THREAD

**Issue by tristanbob** [Graylog2/graylog2-images#33]
NGINX currently listens on port 80 without encryption.  Users who want to run Graylog in production will want to encrypt their passwords, especially if they are using the amazingly simple LDAP integration.

1) The appliance should generate a self-signed cert on first boot.
2) NGINX should redirect port 80 to port 443
3) NGINX should listen on 443 using the self-signed cert

This will enable users to use Graylog securely from day 1.   In addition, it will make it simpler to transition to a valid signed SSL certificate by following the example of the self-signed certs.

**Comment by mariussturm** [comment]
Implemented here: https://github.com/Graylog2/omnibus-graylog2/commit/8fdcbac353b7c37340b1b7515e81487da15ae3f2 will be part of the next version.
