### ISSUE TITLE
Default login/password not working

### ISSUE THREAD

**Issue by Ryotsuke** [Graylog2/graylog2-images#40]
http://screenshots.ryotsuke.ru/scr_56400e0a734d.png
Downloaded from https://packages.graylog2.org/releases/graylog2-omnibus/ova/graylog.ova, started with VMWare 10
admin/admin is not working

Also see there is no address, only "http://" in prompt

**Comment by chuckleb** [comment]
Can you try 
http://IPADDRESS:9000 

Where IP is the address of the VM? It should fire up a web server listening for the login. The admin/admin login is for the web interface, I'm not sure if there is one for ssh.

**Comment by Ryotsuke** [comment]
Still nothing
http://screenshots.ryotsuke.ru/scr_f08f98055160.png
http://192.168.229.134:9000/ same as http://192.168.229.134/

**Comment by chuckleb** [comment]
Did you wait a few minutes for all the services to start up? It can take a bit since there are many pieces. Lastly, the ssh username/password are: ubuntu 
This is what I see from the readme file. You could try to ssh in and confirm things are running properly.

**Comment by Ryotsuke** [comment]
SSH worked. Could you guide what to check next?
http://screenshots.ryotsuke.ru/scr_e17a7e8510d0.png

**Comment by Ryotsuke** [comment]
Also ubuntu/ubuntu is working in VM directly. The VM prompt is misleading, it tells about web password and sugests to enter credentials below, so I just entered what occured to be web credentials

**Comment by Ryotsuke** [comment]
Also I can't see any graylog services. Is VM supposed to have all them configured and running?
http://screenshots.ryotsuke.ru/scr_c6e3473c28cc.png

**Comment by Ryotsuke** [comment]
Seems I've finally figured it out
Please see first screenshot again. It looks first time no network was configured and graylog failed to configure and setup itself. I've powered down, changed VM settings and got network running. 
To make graylog running i ran `reconfigure` command and it has successfully started up.

**Comment by mariussturm** [comment]
Thanks guys for helping each other! I will try to rephrase the console message to make it more clear.

**Comment by scorpio4u-dev** [comment]
This is still an issue when DHCP is not available.
