### ISSUE TITLE
How can I change some field of Graylog configure in MongoDB in this image?

### ISSUE THREAD

**Issue by ourlord** [Graylog2/graylog2-images#41]
For some reason I wish to directly change some configures for Graylog in MongoDB. I found the binary file under /opt/graylog/mongodb/bin/mongo to access the mongodb shell but only can see a database called test. 
So how can I get access to the "real" mongodb stored settings for Graylog?

**Comment by mariussturm** [comment]
Could you please provide some more context? What exactly do you want to achieve? Accessing the mongodb directly is almost always the wrong approach.

**Comment by ourlord** [comment]
My graylog server is set as a vm in my laptop. And the IP address for the graylog vm cannot be static due to my network environment. I found that there is always an invalid IP address(the first IP address when I begin running graylog from this image) hanging around when I did a "graylog-ctl list-servers". 
This doesn't bother me for now because I am only playing around with one node. I wonder if I try to run a multinode environment, this will be an issue. So I wish I could remove this IP address from the servers list or something.
I try to edit some conf file under /opt/graylog/conf but still, that IP address won't go away even my vm's IP keeps changing from time to time.

Example:
If I try,
$ graylog-ctl list-servers
***.***.***.100
***.***.***.123
123 is current IP for graylog. 100 is the IP when I first run this image.

**Comment by mariussturm** [comment]
You can simply re-run `graylog-ctl reconfigure` to update all configurations to the new IP

**Comment by ourlord** [comment]
Yup, actually I did this when my graylog vm IP changes. But still, the old one stays there for some reason when I try "list-servers". 
Btw, the reconfigure command will automatically detect the new IP and changes the conf? Because I usually manually change the conf file with new IP address then run reconfigure command.

**Comment by mariussturm** [comment]
Yes it renders all configuration files. So if you first edit the file manually and then run `reconfigure` your changes are overwritten.
But the command takes notice of a change IP address and adopt the configuration where possible.

**Comment by ourlord** [comment]
Sounds good enough for me now. Should close this one. Thank you so much!
