### ISSUE TITLE
How can I update Elastic Search if I built Graylog2 server from this image?

### ISSUE THREAD

**Issue by ourlord** [Graylog2/graylog2-images#42]
There are some comments from Internet that needs me to do a "add-apt-repo", but by default Ubuntu server cannot do this. And I am trying to keep things simple. I tried to download the latest version of ES and replace the original one from "/opt/graylog/elasticsearch" but this won't work. I cannot connect to both Graylog sever and ES (I did stop all services, copy new ES into the directory and restart them).

**Comment by mariussturm** [comment]
We bundle all related software that is needed for running Graylog in one package. There is no need to update a single component. You can update the whole bundle like documented here: https://github.com/Graylog2/graylog2-images/tree/master/ova#upgrade-graylog

**Comment by mariussturm** [comment]
Closing, because this is no bug.
