### ISSUE TITLE
Docker container contains nested JREs

### ISSUE THREAD

**Issue by dfch** [Graylog2/graylog2-images#45]
Not really a bug, but something I came across when I wanted to update the underlying JVM from v1.7 to v1.8.

When you do a `find / -name java` you will notice that there are two JREs installed inside the Docker image:

	root@e220459c899d:/opt/graylog/plugin# find / -name java
	/opt/graylog/embedded/jre/jre/bin/java
	/opt/graylog/embedded/jre/bin/java
	/opt/graylog/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/spec/data/cookbooks/java
	/opt/graylog/embedded/lib/ruby/gems/2.1.0/gems/coderay-1.1.0/lib/coderay/scanners/java

Both java versions are exactly the same:

	root@e220459c899d:/opt/graylog/plugin# /opt/graylog/embedded/jre/jre/bin/java -version
	java version "1.7.0_71"
	Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
	Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)
	root@e220459c899d:/opt/graylog/plugin# /opt/graylog/embedded/jre/bin/java -version
	java version "1.7.0_71"
	Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
	Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)

However, only one of them is actually used:

	graylog    486  0.7  3.2 3746688 159808 ?      Ssl  Mar02  23:27 /opt/graylog/embedded/jre/bin/java -Xms256m -Xmx1g -Xss256k -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSIni
	graylog    573  1.0  9.3 2606504 456776 ?      Ssl  Mar02  32:05 /opt/graylog/embedded/jre/bin/java -Xms1024m -Xmx1024m -XX:MaxPermSize=256m -XX:ReservedCodeCacheSize=128m -Duser.dir=/opt/graylog/web -

What is strange that these two versions are actually nested inside each other. My questions:

* Is this by design? 
* Which version would I have to change if I wanted to update to v1.8?
* Is this unintentionally or some kind of leftover?

When I look at the `phusion/baseimage:0.9.15` image there is no JVM. So maybe that slipped in through the `dpkg -i graylog_latest.deb` install? (so maybe this is the wrong repo to post the issue).

side note: the reason for wanting to update the JVM is twofold:
1. approaching end of life support of JVM 1.7
2. we are using plugins that make use of JVM 8 features

Just wanted to point this out. You can close it if you do not bother. Regards, Ronald

**Comment by mariussturm** [comment]
This is the structure that comes out of the server-jre package. The deeper jre/ directory is needed for the runtime. To update the JRE you can simply extract a newer version from here http://www.oracle.com/technetwork/java/javase/downloads/server-jre8-downloads-2133154.html over /opt/graylog/embedded/jre

However we will upgrade to Java 8 soon!

**Comment by dfch** [comment]
thanks for the quick reply and good news regarding the planned update to Java 8!
