### ISSUE TITLE
Graylog.conf in OVA 1.0 is missing values compared to the 1.0 conf file

### ISSUE THREAD

**Issue by tristanbob** [Graylog2/graylog2-images#47]
The conf file included in the 1.0 OVA image is missing some values compared to the graylog 1.0 packages.   I have not generated a full list of them, but the most obvious missing options are related to "rotation_strategy".

Here are the contents of "/opt/graylog/conf/graylog.conf":
https://gist.github.com/tristanbob/c6e05fd263f9e7e8728b

Here are the contents of that file from the source:
https://github.com/Graylog2/graylog2-server/blob/master/misc/graylog2.conf

Thanks!

**Comment by mariussturm** [comment]
Fixed in current OVA
