### ISSUE TITLE
User permissions problem

### ISSUE THREAD

**Issue by mariussturm** [Graylog2/graylog2-images#48]
Hi,

I create another user with either read or admin permissions, when I try to access any saved dashboards, I get the following error message below. I also tried exposing the TCP port 12900 to the localhost's IP 10.64.7.36. Is there anything else I need to configure or changed? See the commands I passed to docker below to run graylog & the docker inspect output. Any help would be greatly appreciated.

Thanks,
Yi

(You caused a org.graylog2.restclient.lib.APIException. API call failed GET http://@172.17.0.4:12900/search/universal/relative?filter=&offset=0&query=75..*%20and%20IMCP&limit=100&range=300&sort=timestamp:desc&range_type=relative returned 403 Forbidden body: {"type":"ApiError","message":"Not authorized"})
DOCKER COMMANDS

docker run -t -p 10.64.7.36:9000:9000 -p 10.64.7.36:12201:12201 -p 10.64.7.36:12900:12900 -p 10.64.7.36:514:514/tcp -p 10.64.7.36:514:514/udp -e GRAYLOG_PASSWORD=RXXXXXXX -v /graylog/data:/var/opt/graylog/data -v /graylog/logs:/var/log/graylog --name graylog graylog2/allinone

########### DOCKER INSPECT OUTPUT ###############

[{
"AppArmorProfile": "",
"Args": [],
"Config": {
"AttachStderr": true,
"AttachStdin": false,
"AttachStdout": true,
"Cmd": [
"/opt/graylog/embedded/share/docker/my_init"
],
"CpuShares": 0,
"Cpuset": "",
"Domainname": "",
"Entrypoint": null,
"Env": [
"GRAYLOG_PASSWORD=RXXXXXXXX",
"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
"HOME=/root",
"DEBIAN_FRONTEND=noninteractive"
],
"ExposedPorts": {
"12201/tcp": {},
"12201/udp": {},
"12900/tcp": {},
"4001/tcp": {},
"514/tcp": {},
"514/udp": {},
"9000/tcp": {}
},
"Hostname": "c73c70cd6501",
"Image": "graylog2/allinone",
"Memory": 0,
"MemorySwap": 0,
"NetworkDisabled": false,
"OnBuild": null,
"OpenStdin": false,
"PortSpecs": null,
"StdinOnce": false,
"Tty": true,
"User": "",
"Volumes": {
"/opt/graylog/plugin": {},
"/var/log/graylog": {},
"/var/opt/graylog/data": {}
},
"WorkingDir": ""
},
"Created": "2015-03-23T15:21:23.301814234Z",
"Driver": "devicemapper",
"ExecDriver": "native-0.2",
"HostConfig": {
"Binds": [
"/graylog/data:/var/opt/graylog/data",
"/graylog/logs:/var/log/graylog"
],
"CapAdd": null,
"CapDrop": null,
"ContainerIDFile": "",
"Devices": [],
"Dns": null,
"DnsSearch": null,
"ExtraHosts": null,
"Links": null,
"LxcConf": [],
"NetworkMode": "bridge",
"PortBindings": {
"12201/tcp": [
{
"HostIp": "10.64.7.36",
"HostPort": "12201"
}
],
"12900/tcp": [
{
"HostIp": "10.64.7.36",
"HostPort": "12900"
}
],
"514/tcp": [
{
"HostIp": "10.64.7.36",
"HostPort": "514"
}
],
"514/udp": [
{
"HostIp": "10.64.7.36",
"HostPort": "514"
}
],
"9000/tcp": [
{
"HostIp": "10.64.7.36",
"HostPort": "9000"
}
]
},
"Privileged": false,
"PublishAllPorts": false,
"RestartPolicy": {
"MaximumRetryCount": 0,
"Name": ""
},
"SecurityOpt": null,
"VolumesFrom": null
},
"HostnamePath": "/var/lib/docker/containers/c73c70cd6501ff18a706cf580977f274cbc92053a9ac039ef704e8f156cc2650/hostname",
"HostsPath": "/var/lib/docker/containers/c73c70cd6501ff18a706cf580977f274cbc92053a9ac039ef704e8f156cc2650/hosts",
"Id": "c73c70cd6501ff18a706cf580977f274cbc92053a9ac039ef704e8f156cc2650",
"Image": "987a654e973ea76c3bbd3417b44a97e74ee93c4882a828bac37b6a5a398e9c0f",
"MountLabel": "system_u:object_r:svirt_sandbox_file_t:s0:c724,c891",
"Name": "/graylog",
"NetworkSettings": {
"Bridge": "docker0",
"Gateway": "172.17.42.1",
"IPAddress": "172.17.0.4",
"IPPrefixLen": 16,
"MacAddress": "02:42:ac:11:00:04",
"PortMapping": null,
"Ports": {
"12201/tcp": [
{
"HostIp": "10.64.7.36",
"HostPort": "12201"
}
],
"12201/udp": null,
"12900/tcp": [
{
"HostIp": "10.64.7.36",
"HostPort": "12900"
}
],
"4001/tcp": null,
"514/tcp": [
{
"HostIp": "10.64.7.36",
"HostPort": "514"
}
],
"514/udp": [
{
"HostIp": "10.64.7.36",
"HostPort": "514"
}
],
"9000/tcp": [
{
"HostIp": "10.64.7.36",
"HostPort": "9000"
}
]
}
},
"Path": "/opt/graylog/embedded/share/docker/my_init",
"ProcessLabel": "system_u:system_r:svirt_lxc_net_t:s0:c724,c891",
"ResolvConfPath": "/var/lib/docker/containers/c73c70cd6501ff18a706cf580977f274cbc92053a9ac039ef704e8f156cc2650/resolv.conf",
"State": {
"ExitCode": 0,
"FinishedAt": "0001-01-01T00:00:00Z",
"Paused": false,
"Pid": 8779,
"Restarting": false,
"Running": true,
"StartedAt": "2015-03-23T15:21:24.501188118Z"
},
"Volumes": {
"/opt/graylog/plugin": "/var/lib/docker/vfs/dir/9586d426fc5836adfa2b42fbdba92104db44554f4510cf07aa455c5d465e0260",
"/var/log/graylog": "/graylog/logs",
"/var/opt/graylog/data": "/graylog/data"
},
"VolumesRW": {
"/opt/graylog/plugin": true,
"/var/log/graylog": true,
"/var/opt/graylog/data": true
}
}

**Comment by mariussturm** [comment]
Hi,
please go as Admin to System->Users and click on the small edit button of the relevant user. There you can edit the Dashboard permissons and allow the user to access the dashboard you created.

**Comment by yicheung** [comment]
Hi,  I did grant them full admin permissions to the dashboard, but seems to still deny them access. Looks like the browser is trying to access the docker container IP 172.17.0.4:12900 ??
Thanks,

**Comment by yicheung** [comment]
OK, never mind, looks I need to delete account and recreate as Admin permissions. Doesn't allow you to modify from read to admin permissions. Thanks for the quick reply.
Cheers
