### ISSUE TITLE
Docker image: admin password can't be changed after the first start

### ISSUE THREAD

**Issue by tzz** [Graylog2/graylog2-images#53]
Since the web UI doesn't allow changing the admin password, I tried:

* edited `graylog-secrets.json` to invalidate the password
* restarted with `docker exec -i -t $(docker ps -q) /usr/bin/graylog-ctl restart`
* initial admin password is still active
* start with an entirely new `allinone` image
* `docker exec -i -t $(docker ps -q) /usr/bin/graylog-ctl set-admin-password newpassword`
* restarted with `docker exec -i -t $(docker ps -q) /usr/bin/graylog-ctl restart graylog-web`
* initial admin password is still active

Is there a proper way to set the admin password?  Should I not be using `graylog-ctl` to restart and stop/start the container instead (which would lose log data during the restart period)?

Thank you!

**Comment by brandongalbraith** [comment]
You should be specifying the admin password as an environment variable at launch time with an environment variable parameter:

```
-e GRAYLOG_PASSWORD=<password>
```

If you plan on perisiting data (you should if you're not testing!), follow the instructions below:
https://github.com/Graylog2/graylog2-images/tree/master/docker#persist-data

**Comment by tzz** [comment]
I know about the startup parameter.  I want to change the admin password after the fact.  For instance, because it's easily visible in the process list and you can also grab it with `docker inspect`.

I am persisting data, yes.  My point about restarting is that it takes the input offline during the restart period, potentially losing data.  If I just restart `graylog-web` then the GELF input will remain online.  I hope that explains it better.

**Comment by mariussturm** [comment]
The admin password is stored in the configuration file of the server. So in any case you have to restart the server. However to change it in a running container you could do `graylog-ctl set-admin-password SuPerSecret` followed by `graylog-ctl reconfigure`. The reconfigure command will write the new config file and restart the server.

**Comment by tzz** [comment]
Aha, perfect!  `reconfigure` did not require me to do a restart either, Chef took care of it I guess.  Thank you so much; I think this would be helpful in the Docker image docs but from my side I'm all set.
