### ISSUE TITLE
List Of Environment Variables That Can Be Passed To Graylog

### ISSUE THREAD

**Issue by brandongalbraith** [Graylog2/graylog2-images#55]
Add directly to README or a link to a list of environment variables that can be passed into the Docker container to configure Graylog. (If such a list exists already, my apologies! I was unable to find it)

**Comment by saidimu** [comment]
Where is the list of Docker env vars?

I'm wondering if I can pass in the Elasticsearch cluster name as an env var.

**Comment by joschi** [comment]
@saidimu You can pass any configuration setting from the Graylog configuration file as environment variable changing it to upper case and adding the prefix `GRAYLOG_`, e. g. `GRAYLOG_ELASTICSEARCH_CLUSTER_NAME` for setting [`elasticsearch_cluster_name`](https://github.com/Graylog2/graylog2-server/blob/2.0.3/misc/graylog.conf#L210-L213).
