### ISSUE TITLE
Support SSL Certificate And Key File Imports

### ISSUE THREAD

**Issue by brandongalbraith** [Graylog2/graylog2-images#56]
Use internal Chef recipe to import SSL support files into exposed `/opt/graylog/conf/nginx/ca` volume (see https://github.com/Graylog2/omnibus-graylog2/pull/9 for details).

**Comment by mariussturm** [comment]
After pulling the latest image you should be able to start a container like this:
`docker run -t -p 443:443 -v /somepath/ca:/opt/graylog/conf/nginx/ca graylog2/allinone`
This will create a snakeoil .crt and .key under /somepath/ca/. Graylog is available via https.
If you replace those files (but keep the filenames!) a new container should pick up your own certificate.

**Comment by brandongalbraith** [comment]
:+1: :+1: :+1: Thanks @mariussturm!!
