### ISSUE TITLE
Restarting services

### ISSUE THREAD

**Issue by illogicalextend** [Graylog2/graylog2-images#61]
Re: docker

Out of curiosity, what is the intended way to restart services on this image with the runsv stuff?

I found a workaround of moving directories out of /opt/graylog/sv/ momentarily and then moving them back to trigger a reload.

**Comment by brandongalbraith** [comment]
`docker exec <container-id> graylog-ctl restart`

**Comment by brandongalbraith** [comment]
@illogicalextend Did the above command work for you?

**Comment by illogicalextend** [comment]
Don't want to test it because everything is in a working state right now but thanks for the answer. I'll try it out if I need to restart in the future.

**Comment by brandongalbraith** [comment]
:+1:
