### ISSUE TITLE
Web UI does not work (graylog nodes disconnected)

### ISSUE THREAD

**Issue by MichaelF25** [Graylog2/graylog2-images#63]
Just downloaded the Vagrantfile and did a `vagrant up`.

After successful finish of vagrant, tried to access the web UI on `http://localhost:9000` but the welcome page reported an error that no node of the cluster is responding. It seems that the internal IP `10.0.2.15` was configured by `graylog-ctl` which is obviously not reachable from my browser.

**Comment by mariussturm** [comment]
Dependend on the machine it can take 1-2 minutes until all services are running fine. If the error persist could you please provide some output from `/var/log/graylog/*`?

**Comment by MichaelF25** [comment]
Ok, so it seems that I was a little impatient ;-). Waiting for a couple of minutes after start of the VM solved the problem.

Many thanks and sorry for any inconvenience!
