### ISSUE TITLE
Automatically create input 

### ISSUE THREAD

**Issue by kimble** [Graylog2/graylog2-images#66]
It would be really neat with a way to automatically create inputs..

**Comment by FDiskas** [comment]
:+1:

**Comment by hepin1989** [comment]
+1 too,but maybe need to think about seacurity too.

**Comment by FDiskas** [comment]
Docker usually used not in production

**Comment by joschi** [comment]
Graylog 1.3.0 will have the capability to load and apply content packs from a directory on startup.

See Graylog2/graylog2-server#1521 for details.
