### ISSUE TITLE
No persistent way to change ES_HEAP_SIZE?

### ISSUE THREAD

**Issue by sheavner** [Graylog2/graylog2-images#67]
Our graylog docker container is taking up more space than I'd like, but I can't memory limit it.

I've tried setting ```-e "ES_HEAP_SIZE=3500m"``` on the docker command line, but it must get reset during the startup scripts and always ends up as  ```ES_HEAP_SIZE=9021m``` when I check /proc/NN/environ, presumably from 
```
/opt/graylog/embedded/cookbooks/graylog/recipes/elasticsearch.rb:    :max_memory => "#{(node.memory.total.to_i * 0.6 ).floor / 1024}m"
```
I've tried setting the container max memory (```--memory=3500m```) and that doesn't seem to override the calculation performed above.  /proc and sysinfo() return the host memory stats, there is no containerized way to retrieve the system limits.  See http://fabiokung.com/2014/03/13/memory-inside-linux-containers/

**Comment by muffl0n** [comment]
@sheavner I just had the same problem, ES_HEAP_SIZE was set to 9050m.
I found a workaround by changing the file /opt/graylog/sv/elasticsearch/run in the container to only use 2G. 

steps to change the file:
* Start the container with mounted volumes: ``docker run -t -p 9000:9000 -p 12201:12201 --name="graylog" -v /data/graylog/data:/var/opt/graylog/data -v /data/graylog/logs:/var/log/graylog graylog2/allinone``
* Copy run-file to /data/graylog/data/: ``docker cp graylog:/opt/graylog/sv/elasticsearch/run /data/graylog/data/``
* Change ``export ES_HEAP_SIZE=9050m`` in /data/graylog/data/run to something more reasonable like ``export ES_HEAP_SIZE=2G``
* Move file from ``/var/opt/graylog/data/run`` to ``/opt/graylog/sv/elasticsearch/run`` in container: ``docker exec graylog mv /var/opt/graylog/data/run /opt/graylog/sv/elasticsearch/run``

Please note: I'm fairly new to docker, so this could surely be improved.

**Comment by sheavner** [comment]
@muffl0n I too put in a terrible local hack that will probably break in the next graylog release.

I pulled /opt/graylog/embedded/cookbooks/graylog/recipes/elasticsearch.rb out to the host filesystem, modified the offending line (```:max_memory => "2048m"```), and mount the modified external file when starting docker.   We rebuild our containers on each restart, changes to the local filesystem are lost.

```
-v /mnt/graylog2/elasticsearch.rb:/opt/graylog/embedded/cookbooks/graylog/recipes/elasticsearch.rb
```

**Comment by mariussturm** [comment]
Latest Docker image allows you to set Elasticsearch memory setting with e.g. `-e ES_MEMORY=1024m`.

**Comment by brandongalbraith** [comment]
:+1: :+1: :+1:

**Comment by muffl0n** [comment]
Thanks for the fix! 
Maybe you could also change the default value? 60% of the hosts memory is quite a lot and surely not needed by most people.

I think it's more expected that ES runs out of memory than ES not starting at all.

**Comment by mariussturm** [comment]
The problem is that this setting is used for _all_ Graylog appliances and not only for the Docker image. Docker is a bit special here because it is the only platform not able to report the correct number of memory it has. But 60% works great on all other platforms like Virtualbox, VMWare, AWS... I will put the ES_MEMORY paramter in the docs so people see that they have to set it.
