### ISSUE TITLE
Unable to add Additional Nodes

### ISSUE THREAD

**Issue by DerrickLamers** [Graylog2/graylog2-images#68]
I have configured a Multi VM setup as mentioned in the documentation but when I attempt to add additional Elasticsearch nodes they are not listed as part of the cluster. Can someone tell me what I am doing wrong? I think there may be an error in the documentation.

**Comment by mariussturm** [comment]
Could you please provide the exact commands you gave on each machine? So that I can try to reconstruct what went wrong? Thanks.

**Comment by mariussturm** [comment]
Closing this because lack of information. Feel free to re-open!
