### ISSUE TITLE
search no data but input get data, GELF_UDP on docker

### ISSUE THREAD

**Issue by lubia** [Graylog2/graylog2-images#71]
I install graylog with (on mac with boot2docker)
```
$ docker pull graylog2/allinone
$ docker run -t \
-p 9000:9000 \
-p 12201:12201 \
-p 9003:9003 \
-p 9003:9003/udp \
-e GRAYLOG_NODE_ID=node-id-001 \
-e GRAYLOG_SERVER_SECRET=somesecretsaltstring \
-e GRAYLOG_TIMEZONE=Asia/Shanghai \
-v /var/opt/graylog/data:/var/opt/graylog/data \
-v /var/log/graylog:/var/log/graylog \
 graylog2/allinone
```

when I send message to server with these golang code (the example from official golang client)

```
package main

import (
	"github.com/Graylog2/go-gelf/gelf"
	"io"
	"log"
	"os"
)

func main() {
	graylogAddr := "boot2docker:9003"
	gelfWriter, err := gelf.NewWriter(graylogAddr)
	if err != nil {
		log.Fatalf("gelf.NewWriter: %s", err)
	}
	log.SetOutput(io.MultiWriter(os.Stderr, gelfWriter))
	log.Printf("logging to stderr & graylog2@'%s'", graylogAddr)
	for i := 0; i < 10000; i++ {
		log.Printf("Hello gray World")
	}
}
```
Then I receive message from Input
![image](https://cloud.githubusercontent.com/assets/2741940/8399977/2a5223fc-1e4a-11e5-9be8-a0da92d800ad.png)

But on search page,there is nothing
![image](https://cloud.githubusercontent.com/assets/2741940/8399990/4e7558da-1e4a-11e5-855c-ddfe34a3ae0a.png)

**Comment by lubia** [comment]
after a few minute,I got 589 items, but i sent 10000 items.
![image](https://cloud.githubusercontent.com/assets/2741940/8400074/4a7d5786-1e4b-11e5-9dea-d90e72fad12a.png)

**Comment by lubia** [comment]
some more infomation, status of Elasticsearch cluster
![image](https://cloud.githubusercontent.com/assets/2741940/8401316/63c11048-1e5f-11e5-8eca-07a30c09c8fb.png)

**Comment by dpayonk** [comment]
I was having a similiar problem after running the container today.  I tested with the TCP input and it worked, but the UDP seems to not be accepting messages.

**Comment by dpayonk** [comment]
@lubia the docker run command needs to be modified to explicitly allow UDP packets.  

docker run -t -p 9000:9000 -p 12201:12201 -p 12201:12201/udp graylog2/allinone

**Comment by lubia** [comment]
@dpayonk  no mistake here
I use 9003 port 
```
-p 9003:9003 \
-p 9003:9003/udp \
```

and input config to 9003

**Comment by mariussturm** [comment]
@lubia as long as _some_ messages are received through the UDP input nothing is wrong imo. By definition UDP drops messages that can't be processed. In you example code you send log messages at maximum speed without any delay. In a real world program something would happen between each log line. When you put something like `time.Sleep(100 * time.Millisecond)` in the for-loop it should work.

**Comment by lubia** [comment]
@mariussturm  Thanks. I test at higher speed and it still work. And i have another question.
Search message has delay,about 3 minutes.Even just 1 single message has sent,it appears 3 minutes later. I also test SyslogUDP input,it appears on real-time.

**Comment by mariussturm** [comment]
There should be no difference between syslog and gelf processing. Graylog is storing messages in a buffer in case Elasticsearch is not capable of receiving messages but this is the same for both protocols. For more general questions please join our Google group or IRC. Thanks!

**Comment by lubia** [comment]
@mariussturm thanks
