### ISSUE TITLE
Request: Graylog AWS Image on AP-Singapore

### ISSUE THREAD

**Issue by mudspot** [Graylog2/graylog2-images#73]
Hi Marius!

Can an AMI for GrayLog be made available for Amazon WS in AP-Singapore?

I can help if Needed.

Best Regards
Terry

**Comment by mariussturm** [comment]
Hi Terry,
I have added southeast-1 to the deployment configuration. Till the next release you can use this AMI: ami-76d3d024

**Comment by mudspot** [comment]
Thank you! I launched it successfully.
