### ISSUE TITLE
qcow2 Installation on Openstack

### ISSUE THREAD

**Issue by mariussturm** [Graylog2/graylog2-images#74]
Anyone has experience in deploying Open Stack ?

I tried installing Graylog2 using qcow installation on my Openstack Server, but I had a problem when i try to access it, it says they need password and public key.

FYI. I already put .pem correctly but they still need password, I already tried password: ubuntu,admin.

Does anyone have a same issue with me ?

ping @ivangerard

**Comment by mariussturm** [comment]
When you launch the instance in OpenStack you have to choose a SSH key under 'Access & Security' this key is used for the `ubuntu` user.

**Comment by ivangerard** [comment]
Hi @mariussturm, 

Thanks for your reply, 

I don't think the problem in SSH key,  Have you ever to install graylog2 at Openstack server ? 

Because when i try several password, the server says Permission Denied (public key, password )

**Comment by mariussturm** [comment]
Username/password is not working on Openstack you have to get the SSH key right. The image is supporting the normal cloud-init process OpenStack is using. If you can deploy other images this one should work as well.

**Comment by ivangerard** [comment]
@mariussturm Yeah marius. There is no problem with other image, only this qcow asking for username and password. =(

Anyone had some issues ?

**Comment by mariussturm** [comment]
What do you mean by 'any download links to install qcow2'? This how you can download the official Graylog image and how you can import it into OpenStack: http://docs.graylog.org/en/latest/pages/installation/openstack.html

**Comment by mariussturm** [comment]
Sorry, can nor reproduce.
