### ISSUE TITLE
Impossible to configure transport_email_web_interface_url for docker image

### ISSUE THREAD

**Issue by scorpp** [Graylog2/graylog2-images#75]
As a result alert emails sent by Graylog contain link with docker internal hostname (e.g. ` http://5f4659f1cc5c/....`) which are not usable.

It would be much appreciated if there was a possibility to set external url with an env var

**Comment by mariussturm** [comment]
This is now in the latest `allinone` container. Please use it like: `-e GRAYLOG_SMTP_SERVER="localhost --web-url=http://my.graylog.host/graylog ...`
