### ISSUE TITLE
VM Appliance Storage Expansion

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog2-images#76]
Copied from Graylog2/graylog2-web-interface#1545
> I have installed Graylog2 via the VM Appliance Package. Ive tried to install it manually, but no success. Anyway, the appliance comes with only 20GB Primary HD where Graylog2 is installed, but 20GB is not enough for me. I need to expand the Graylog2 storage to about 200GB.
What would be the best way, and how can I go about it? I see in the notes that if I want more storage, I must mount another drive to /var/opt/graylog/data.
I have no clue how to do that part. Also, I cannot edit the VM Storage for Graylog2 appliance, as its grayed out.
> 
> Can someone tell me or give me a link to where it shows what to do? I would really appreciate the help.
Thanks....

**Comment by mariussturm** [comment]
@cpaunescu could you please provide some more informations about your environment? Is this a VMWare appliance or AWS or something else? Adding more storage depends heavily on the hypervisor.

**Comment by rikmer** [comment]
@joschi: I dont know if the VMWare appliance is configured with LVM. If it is you can just add a second virtual drive to the VM and expand the lvm partition using this new space. Like this:
http://www.joomlaworks.net/blog/item/168-resizing-the-disk-space-on-ubuntu-server-vms

**Comment by mariussturm** [comment]
This is documented here: http://docs.graylog.org/en/1.3/pages/installation/graylog_ctl.html#extend-disk-space
