### ISSUE TITLE
the docker image always start up with 0 node

### ISSUE THREAD

**Issue by hepin1989** [Graylog2/graylog2-images#78]
```
No Graylog servers available. Cannot log in.
```
and with 
```
0 of 1 nodes connected.
```

command is 
```
docker run -t -p 9000:9000 -p 12201:12201 -p 12202:12202/udp graylog2/allinone

```

**Comment by mariussturm** [comment]
Are there any errors when you run the container in foreground?

**Comment by mariussturm** [comment]
Just tested this, there is no general probelm. Reasons for no server running could be insufficiant memory settings or other system limitations.
