### ISSUE TITLE
Configuring SMTP server in virtual appliance throws error

### ISSUE THREAD

**Issue by rikmer** [Graylog2/graylog2-images#79]
sudo graylog-ctl set-email-config 192.168.1.10
/opt/graylog/embedded/lib/ruby/2.1.0/uri/common.rb:1234:in `URI': bad argument (expected URI object or URI string) (ArgumentError)
        from (eval):53:in `block (2 levels) in load_files'
        from /opt/graylog/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.0.7/lib/omnibus-ctl.rb:145:in `call'
        from /opt/graylog/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.0.7/lib/omnibus-ctl.rb:145:in `block in add_command'
        from /opt/graylog/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.0.7/lib/omnibus-ctl.rb:366:in `run'
        from /opt/graylog/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.0.7/bin/omnibus-ctl:27:in `<top (required)>'
        from /opt/graylog/embedded/bin/omnibus-ctl:23:in `load'
        from /opt/graylog/embedded/bin/omnibus-ctl:23:in `<main>'

**Comment by mariussturm** [comment]
Thanks! This is solved in the latest OVA and Docker image. Please pull/download again.

**Comment by deucesapp** [comment]
We are running on the OVA image that had the problem (installed Monday of this week), is there a way to upgrade our existing VM without losing the logs we've collected this week? We also are unable to set the SMTP server via graylog-ctl (and get an error setting graylog-ctl set-retention -size=1 OR -time=24 -incices=10 -journal=5 as well).

**Comment by mariussturm** [comment]
Please follow the upgrade instructions here: http://docs.graylog.org/en/latest/pages/installation/graylog_ctl.html#upgrade-graylog
