### ISSUE TITLE
 invalid option: --no-ssl

### ISSUE THREAD

**Issue by phlegx** [Graylog2/graylog2-images#80]
With ```docker-compose``` I try to bring up a graylog server. Here is the snippet for the compose file:

https://gist.github.com/anonymous/2df01d2b1add332428e3

But when I try to ```docker-compose up``` I the the error that ```--no-ssl``` is an invalid option, even though it should be valid. See the full error here btw. https://gist.github.com/anonymous/d25c3d9cd4a2956dfbec

all the best
ps

**Comment by mariussturm** [comment]
`docker-compose` is doing some funny stuff with double quotes, please change your `docker-compose.yml` to:

```
environment:
    - GRAYLOG_PASSWORD=PASSWORD
    - GRAYLOG_TIMEZONE=Europe/Vienna
    - GRAYLOG_SMTP_SERVER=mail.example.com --port=587 --user=user@example.com --password=PASS --no-ssl
```

**Comment by phlegx** [comment]
thanks  @mariussturm!

**Comment by phlegx** [comment]
@mariussturm  Sorry I could just try it out now. I stumled upon another errors that appears, using the same configuration as linked above and only remove the double quotes as you suggested. Here is the error:

```
graylog_1 | *** Booting runit daemon...
graylog_1 | *** Runit started as PID 6
graylog_1 | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
graylog_1 | *** Running /etc/rc.local...
graylog_1 | /opt/graylog/embedded/lib/ruby/2.1.0/uri/common.rb:1234:in `URI': bad argument (expected URI object or URI string) (ArgumentError)
graylog_1 | 	from (eval):53:in `block (2 levels) in load_files'
graylog_1 | 	from /opt/graylog/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.0.7/lib/omnibus-ctl.rb:145:in `call'
graylog_1 | 	from /opt/graylog/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.0.7/lib/omnibus-ctl.rb:145:in `block in add_command'
graylog_1 | 	from /opt/graylog/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.0.7/lib/omnibus-ctl.rb:366:in `run'
graylog_1 | 	from /opt/graylog/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.0.7/bin/omnibus-ctl:27:in `<top (required)>'
graylog_1 | 	from /opt/graylog/embedded/bin/omnibus-ctl:23:in `load'
graylog_1 | 	from /opt/graylog/embedded/bin/omnibus-ctl:23:in `<main>'
graylog_1 | *** /etc/rc.local failed with status 1
graylog_1 | 
graylog_1 | *** Killing all processes...
log_graylog_1 exited with code 1
```
Maybe you know why this happens too!

thanks in advance
ps

**Comment by mariussturm** [comment]
This was fixed today, please pull the latest `graylog2/allinone` image.

**Comment by phlegx** [comment]
Yes now it works, thank you very much!
