### ISSUE TITLE
Official way to alter "Xmx" options for Java?

### ISSUE THREAD

**Issue by LordMike** [Graylog2/graylog2-images#82]
Hi,

I've used the OVA image on a VMWare ESXi and given it 4GB memory.

I'm hitting some "Error starting this input: Cannot allocate memory." errors when I have three inputs running. A `free -m` command on the vm shows 2GB free, so I wanted to increase the Xmx option for the `graylog-server`.

I found the embedded `GRAYLOG_SERVER_JAVA_OPTS` variable, but it seems like it's not intended to be edited this way. Is there an official way to control memory?

Normally I'd expect an `/etc/defaults/graylog-server` file - but that's not present.

Mike.

**Comment by mariussturm** [comment]
Have a look here: https://github.com/Graylog2/graylog2-images/issues/84
