### ISSUE TITLE
Static IP reverts back to DHCP

### ISSUE THREAD

**Issue by combsbj** [Graylog2/graylog2-images#83]
After installing the OVF and following documentation (http://docs.graylog.org/en/1.1/pages/installation/graylog_ctl.html) to assign a static IP, the appliance reverts back to a DHCP address after a few hours.

I suspect that the steps in the document are not sufficient to disable the DHCP client, and that an additional step should be added to the documentation to stop it.

**Comment by combsbj** [comment]
graylog-web-interface v1.1.6 (2e264c2) (Oracle Corporation 1.8.0_51 / Linux 3.19.0-25-generic) on graylog

**Comment by mariussturm** [comment]
Thanks for the report! This was fixed in the current documentation.
