### ISSUE TITLE
OVA: Set JVM

### ISSUE THREAD

**Issue by haricharan123** [Graylog2/graylog2-images#84]
I have started up with Ova for graylog, I find that i need to increase the JVM on the  graylog-server node. How do i go about it. is there a config file that I can set somewhere?

Update: I updated the script in (```/opt/graylog/server/bin/graylogctl```)  with ``` -Djava.library.path=./../lib/sigar -Xms2g -Xmx2g -XX:NewRatio=1 -XX:PermSize=256m -XX:MaxPermSize=512m -server -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow```

However JVM is still using  972.8 MB heap space and will not attempt to use more than  972.8 MB

**Comment by haricharan123** [comment]
Set it at /opt/graylog/service/graylog-server/run 

thanks to 

https://groups.google.com/forum/?hl=en#!topic/graylog2/Ob6p6lffUis

**Comment by mariussturm** [comment]
For the upcoming 1.2 release, you can set this in `/etc/graylog/graylog-settings.json`:

```
"custom_attributes": {
  "graylog-server": {
    "memory": "1500m"
  },
  "elasticsearch": {
    "memory": "3g"
  }
}
```

Afterwards a `graylog-ctl reconfigure` sets the values. In this way the settings can be persisted.
Or you can try it today already with the `beta/rc` OVA: https://github.com/Graylog2/graylog2-images/tree/master/ova
