### ISSUE TITLE
Persisting a fix for "too low open file limit" for docker

### ISSUE THREAD

**Issue by javadan** [Graylog2/graylog2-images#86]
I cannot find any solution to this.  I'm sure I'm close, but I am still no cigar.

I logged into the docker container and modified /etc/security/limits.conf 
but I can't work out how to restart elasticsearch.  If I kill it with SIGTERM, it immediately starts up again, so I can't even change the -D params.

So I'm not sure how I'd follow the elasticsearch instructions that suggest set -Des.max-open-files to true

If I try change the OS limit with "`ulimit -n 65535`", I get:
`bash: ulimit: open files: cannot modify limit: Operation not permitted`

If I try restart it another way,
`curl -XPOST 'http://localhost:9200/_cluster/nodes/_local/_restart'`
I get:
`{"error":"ElasticsearchIllegalStateException[restart is disabled (for now) ....]","status":500}`

If I restart the docker instance, all my changes to limits.conf disappear.

So I'm stuck.  Has anyone worked this out?

**Comment by mariussturm** [comment]
Could you please provide some more informations of your setup? This looks like your Docker _host_ doesn't allow the container to open more file handles.

**Comment by javadan** [comment]
Thanks Marius for the reply.  

Distributor ID: CentOS
Description:    CentOS release 6.7 (Final)
Release:        6.7
Codename:       Final

My kernel is '2.6.32-573.3.1.el6.x86_64'

I'm not sure what permissions are stopping the docker container, but I'll keep looking.  Let me know if you think you might know what it is.  Thanks

**Comment by mariussturm** [comment]
From the offical docu: https://docs.docker.com/installation/centos
You should run at least a 3.x kernel, means CentOS 7. Maybe you could check if that behaves differently.
