### ISSUE TITLE
Switch VMware image to use SCSI instead of IDE

### ISSUE THREAD

**Issue by peterloron** [Graylog2/graylog2-images#87]
The current rc VMware image for Graylog has the disk set up with an IDE controller. Please consider switching that to the SCSI controller. This is very well supported in current OSes, and it avoids problems with our NetApp SnapManager software. Thanks!

**Comment by mariussturm** [comment]
Sorry can't do this upstream. I did some experiments but the SCSI controller is not detected properly by all hypervisor(/versions). To reach the same compatibility, we have today with the IDE controller, we would need to invest alot of time and testing for a comparably lot benefit.
But you can easily work around this locally. Simply create an empty Ubuntu VM with the controller of choice and install the Graylog Omnibus package: https://github.com/Graylog2/omnibus-graylog2
This is basically all we do on the official appliances.
