### ISSUE TITLE
[Docker] Allow setting max journal size

### ISSUE THREAD

**Issue by DaveWM** [Graylog2/graylog2-images#92]
I'm having a problem with the default journal size (1GB) being too low, and graylog slows to a crawl when it hits the limit. Is there any way of setting the max journal size when running the docker container? It's not listed in the "additional options" section in the docs.

I had a look at the dockerfile but couldn't see where it's using the environment variables you assign to the container, if someone can point me in the right direction I can try and make a PR.

**Comment by joschi** [comment]
You can override Graylog configuration settings with appropriately named environment variables (using the prefix `GRAYLOG2_`; for historic reasons). In you specific case, it's possible to override the `message_journal_max_size` setting (https://github.com/Graylog2/graylog2-server/blob/1.2.1/misc/graylog2.conf#L258-L262) with the `GRAYLOG2_MESSAGE_JOURNAL_MAX_SIZE` environment variable which you can pass to Docker like documented at https://docs.docker.com/reference/run/#env-environment-variables

**Comment by DaveWM** [comment]
@joschi thanks very much, thats a massive help
