### ISSUE TITLE
Add installation source for the 1.3 release

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-images#94]
Graylog 1.3 will have a new `installation_source` configuration variable. This tells Graylog how it has been deployed. The content of the option will be logged on startup to help debugging issues.

```
2015-11-11T12:35:03.820Z INFO  [ServerBootstrap] Graylog server 1.3.0-SNAPSHOT (d607920) starting up (JRE: Oracle Corporation 1.7.0_79 on Linux 3.16.0-30-generic, installed from: deb)
```
This options needs to be set for the different omnibus deployments as well. The OS packages are setting the `graylog2.installation_source` system property when starting the process.

See: https://github.com/Graylog2/fpm-recipes/commit/3df5e5f20a4b467110c86d1e2f88d0c3e13dce39

We use `deb` and `rpm` for the OS packages. The appliances should use something like `ova`, `ami`, `docker` and `qcow`.

**Comment by mariussturm** [comment]
Done.
