### ISSUE TITLE
Amazon AWS AMI Update Instructions

### ISSUE THREAD

**Issue by huhu1884** [Graylog2/graylog2-images#95]
I currently have an EC2 instance running your packaged AMI which is great and I'm very thankful for. Now though I'm trying to update that instance. The AMI utilises amazon linux, and your AWS page links back to the upgrade instructions page here: http://docs.graylog.org/en/1.2/pages/installation/graylog_ctl.html#upgrade-graylog

But these instructions utilise debian packages which aren't compatible with amazon linux, and my installation doesn't even include graylog-ctl. Is there a different upgrade process for the AWS AMI, or am I just so behind the times there's no upgrade path available to me?
https://github.com/Graylog2/graylog2-images/tree/master/aws

**Comment by mariussturm** [comment]
Sorry, we never shipped images based on Amazon linux, this must be a community appliance. If there is no update available please consider to switch to one of our offical images.
