### ISSUE TITLE
presisting graylog docker in windows 7 breaks

### ISSUE THREAD

**Issue by NahumLitvin** [Graylog2/graylog2-images#96]
I use the following script

docker pull graylog2/allinone  
docker run -t --name graylog_allinone --rm -p 12900:12900 -p 25:25 -p 9000:9000 -p 12201:12201 -p 12201:12201/udp -e GRAYLOG_NODE_ID=GRAYLOG_NODE_ID -e GRAYLOG_SERVER_SECRET=GRAYLOG_SERVER_SECRET -v /c/Users/graylog/plugin:/opt/graylog/plugin -v /c/Users/graylog/data:/var/opt/graylog/data -v /c/Users/graylog/logs:/var/log/graylog  graylog2/allinone

I get a message No Graylog servers available. Cannot log in.

No configured node was ever reached.

**Comment by mariussturm** [comment]
Looks like Elasticsearch or Graylog-server is not running in your container. Could you please check /var/log/graylog/elasticsearch/current and /var/log/graylog/server/current fort errors?

**Comment by mariussturm** [comment]
No user feedback, closing!
